// @ts-nocheck
import type { Pool } from 'pg';
import type { ManufacturingExecutionRepository } from '../../../domain/contracts/manufacturing-execution.js';
import { withTenantContext } from '../tenant-context.js';
import { ValidationError, ConflictError, NotFoundError } from '../../../domain/errors.js';

const map=(r:any)=>r ? {...r, plannedQuantity:r.plannedQuantity==null?undefined:Number(r.plannedQuantity), quantity:r.quantity==null?undefined:Number(r.quantity)} : null;

export class PostgresManufacturingExecutionRepository implements ManufacturingExecutionRepository {
 constructor(private readonly pool:Pool, private readonly tenantContextKey='app.current_tenant_id'){}
 private tx(tenantId:string, actorUserId:string|undefined, cb:any){ return withTenantContext(this.pool,this.tenantContextKey,tenantId,cb,{userId:actorUserId}); }

 async createCapability(i:any){return this.tx(i.tenantId,i.userId,async c=>{const r=await c.query(`INSERT INTO manufacturing_machine_capabilities(tenant_id,branch_id,machine_id,operation_code,capability_name,min_value,max_value,parameter_uom,tooling_id,fixture_id,status,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12) RETURNING *`,[i.tenantId,i.branchId,i.machineId,i.operationCode,i.capabilityName??null,i.minValue??null,i.maxValue??null,i.parameterUom??null,i.toolingId??null,i.fixtureId??null,i.status??'ACTIVE',i.userId]);return r.rows[0];});}
 async listCapabilities(ctx:any,q:any){return this.tx(ctx.tenantId,undefined,async c=>{const v=[ctx.tenantId,ctx.branchId];let w='c.tenant_id=$1 AND c.branch_id=$2 AND c.is_deleted=false';if(q.machineId){v.push(q.machineId);w+=` AND c.machine_id=$${v.length}`;}if(q.operationCode){v.push(q.operationCode);w+=` AND c.operation_code=$${v.length}`;}const count=await c.query(`SELECT count(*)::int count FROM manufacturing_machine_capabilities c WHERE ${w}`,v);v.push((q.page-1)*q.pageSize,q.pageSize);const rows=await c.query(`SELECT c.*,m.code machine_code,m.name machine_name FROM manufacturing_machine_capabilities c JOIN manufacturing_machines m ON m.id=c.machine_id AND m.tenant_id=c.tenant_id WHERE ${w} ORDER BY c.operation_code,c.id OFFSET $${v.length-1} LIMIT $${v.length}`,v);return {items:rows.rows,total:Number(count.rows[0].count)};});}

 async createProcess(i:any){return this.tx(i.tenantId,i.userId,async c=>{const r=await c.query(`INSERT INTO manufacturing_process_details(tenant_id,branch_id,item_id,revision,drawing_number,drawing_revision,input_weight,finished_weight,gross_weight,burnt_percent,work_instruction,pfd,status,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$14) RETURNING *`,[i.tenantId,i.branchId,i.itemId,i.revision,i.drawingNumber??null,i.drawingRevision??null,i.inputWeight??null,i.finishedWeight??null,i.grossWeight??null,i.burntPercent??null,i.workInstruction??null,i.pfd??null,i.status??'DRAFT',i.userId]);return r.rows[0];});}
 async addRoutingOperation(i:any){return this.tx(i.tenantId,i.userId,async c=>{const p=await c.query('SELECT id FROM manufacturing_process_details WHERE tenant_id=$1 AND branch_id=$2 AND id=$3 AND is_deleted=false',[i.tenantId,i.branchId,i.processDetailId]);if(!p.rowCount)throw new NotFoundError('Process detail not found.');const r=await c.query(`INSERT INTO manufacturing_routing_operations(tenant_id,branch_id,process_detail_id,sequence_no,operation_code,operation_description,machine_group,machine_code,manpower,cycle_time_seconds,setup_time_seconds,allowance_percent,overhead_seconds,batch_quantity,tooling_description,work_instruction,process_parameters,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$18) RETURNING *`,[i.tenantId,i.branchId,i.processDetailId,i.sequenceNo,i.operationCode,i.operationDescription,i.machineGroup??null,i.machineCode??null,i.manpower??null,i.cycleTimeSeconds??null,i.setupTimeSeconds??null,i.allowancePercent??null,i.overheadSeconds??null,i.batchQuantity??null,i.toolingDescription??null,i.workInstruction??null,JSON.stringify(i.processParameters??{}),i.userId]);return r.rows[0];});}
 async getProcess(ctx:any,id:string){return this.tx(ctx.tenantId,undefined,async c=>{const p=await c.query('SELECT * FROM manufacturing_process_details WHERE tenant_id=$1 AND branch_id=$2 AND id=$3 AND is_deleted=false',[ctx.tenantId,ctx.branchId,id]);if(!p.rowCount)throw new NotFoundError('Process detail not found.');const ops=await c.query('SELECT * FROM manufacturing_routing_operations WHERE tenant_id=$1 AND process_detail_id=$2 ORDER BY sequence_no',[ctx.tenantId,id]);return {...p.rows[0],routing:ops.rows};});}

 async createWorkOrder(i:any){return this.tx(i.tenantId,i.userId,async c=>{const r=await c.query(`INSERT INTO manufacturing_work_orders(tenant_id,branch_id,work_order_number,customer_id,item_id,process_detail_id,planned_quantity,scheduled_start,scheduled_end,priority,notes,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$12) RETURNING *`,[i.tenantId,i.branchId,i.workOrderNumber,i.customerId??null,i.itemId,i.processDetailId,i.plannedQuantity,i.scheduledStart??null,i.scheduledEnd??null,i.priority??0,i.notes??null,i.userId]);return r.rows[0];});}
 async scheduleWorkOrder(i:any){return this.tx(i.tenantId,i.userId,async c=>{const wo=await c.query('SELECT * FROM manufacturing_work_orders WHERE tenant_id=$1 AND branch_id=$2 AND id=$3 AND is_deleted=false FOR UPDATE',[i.tenantId,i.branchId,i.workOrderId]);if(!wo.rowCount)throw new NotFoundError('Work order not found.');if(['CANCELLED','COMPLETED'].includes(wo.rows[0].status))throw new ConflictError('Work order cannot be scheduled in its current state.');const ops=await c.query('SELECT * FROM manufacturing_routing_operations WHERE tenant_id=$1 AND process_detail_id=$2 ORDER BY sequence_no',[i.tenantId,wo.rows[0].process_detail_id]);if(!ops.rowCount)throw new ValidationError('Work order routing has no operations.');for(const op of ops.rows){await c.query(`INSERT INTO manufacturing_task_sheets(tenant_id,branch_id,work_order_id,routing_operation_id,sequence_no,machine_id,planned_quantity,status,created_by,updated_at) VALUES($1,$2,$3,$4,$5,NULL,$6,'PENDING',$7,now()) ON CONFLICT (tenant_id,work_order_id,routing_operation_id) DO NOTHING`,[i.tenantId,i.branchId,i.workOrderId,op.id,op.sequence_no,wo.rows[0].planned_quantity,i.userId]);}const r=await c.query(`UPDATE manufacturing_work_orders SET status='SCHEDULED',updated_at=now(),updated_by=$1,version=version+1 WHERE id=$2 AND tenant_id=$3 RETURNING *`,[i.userId,i.workOrderId,i.tenantId]);return r.rows[0];});}
 async listWorkOrders(ctx:any,q:any){return this.tx(ctx.tenantId,undefined,async c=>{const v=[ctx.tenantId,ctx.branchId];let w='tenant_id=$1 AND branch_id=$2 AND is_deleted=false';if(q.status){v.push(q.status);w+=` AND status=$${v.length}`;}if(q.search){v.push('%'+q.search+'%');w+=` AND work_order_number ILIKE $${v.length}`;}const count=await c.query(`SELECT count(*)::int count FROM manufacturing_work_orders WHERE ${w}`,v);v.push((q.page-1)*q.pageSize,q.pageSize);const rows=await c.query(`SELECT * FROM manufacturing_work_orders WHERE ${w} ORDER BY created_at DESC,id DESC OFFSET $${v.length-1} LIMIT $${v.length}`,v);return {items:rows.rows,total:Number(count.rows[0].count)};});}

 async getTaskSheet(ctx:any,id:string){return this.tx(ctx.tenantId,undefined,async c=>{const r=await c.query(`SELECT t.*,wo.work_order_number,wo.item_id,ro.operation_code,ro.operation_description,ro.process_parameters FROM manufacturing_task_sheets t JOIN manufacturing_work_orders wo ON wo.id=t.work_order_id AND wo.tenant_id=t.tenant_id JOIN manufacturing_routing_operations ro ON ro.id=t.routing_operation_id AND ro.tenant_id=t.tenant_id WHERE t.tenant_id=$1 AND t.branch_id=$2 AND t.id=$3`,[ctx.tenantId,ctx.branchId,id]);if(!r.rowCount)throw new NotFoundError('Task sheet not found.');return r.rows[0];});}
 async updateTaskStatus(i:any){return this.tx(i.tenantId,i.userId,async c=>{const r=await c.query(`UPDATE manufacturing_task_sheets SET status=$1,updated_at=now(),version=version+1 WHERE tenant_id=$2 AND branch_id=$3 AND id=$4 AND version=$5 RETURNING *`,[i.status,i.tenantId,i.branchId,i.taskSheetId,i.expectedVersion]);if(!r.rowCount)throw new ConflictError('Task sheet not found or version is stale.');return r.rows[0];});}

 async createMaterialRequisition(i:any){return this.tx(i.tenantId,i.userId,async c=>{const r=await c.query(`INSERT INTO manufacturing_material_requisitions(tenant_id,branch_id,requisition_number,work_order_id,notes,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$6) RETURNING *`,[i.tenantId,i.branchId,i.requisitionNumber,i.workOrderId,i.notes??null,i.userId]);for(const l of i.lines){await c.query(`INSERT INTO manufacturing_material_requisition_lines(tenant_id,branch_id,requisition_id,item_id,required_quantity,min_quantity,max_quantity,heat_lot_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[i.tenantId,i.branchId,r.rows[0].id,l.itemId,l.requiredQuantity,l.minQuantity??null,l.maxQuantity??null,l.heatLotId??null]);}return r.rows[0];});}
 async issueMaterial(i:any){return this.tx(i.tenantId,i.userId,async c=>{const key=i.operationKey;const existing=await c.query('SELECT * FROM manufacturing_material_issues WHERE tenant_id=$1 AND operation_key=$2',[i.tenantId,key]);if(existing.rowCount)return existing.rows[0];const line=await c.query('SELECT * FROM manufacturing_material_requisition_lines WHERE tenant_id=$1 AND id=$2 FOR UPDATE',[i.tenantId,i.requisitionLineId]);if(!line.rowCount)throw new NotFoundError('Material requisition line not found.');const l=line.rows[0];if(Number(l.issued_quantity)+Number(i.quantity)>Number(l.required_quantity))throw new ValidationError('Issue quantity exceeds requisition balance.');const stock=await c.query('SELECT * FROM inventory_stock WHERE tenant_id=$1 AND warehouse_id=$2 AND item_id=$3 FOR UPDATE',[i.tenantId,i.warehouseId,l.item_id]);if(!stock.rowCount || Number(stock.rows[0].on_hand_quantity)-Number(stock.rows[0].reserved_quantity)<Number(i.quantity))throw new ConflictError('Insufficient available stock.');await c.query('UPDATE inventory_stock SET on_hand_quantity=on_hand_quantity-$1,version=version+1,updated_at=now(),updated_by=$2 WHERE id=$3',[i.quantity,i.userId,stock.rows[0].id]);await c.query(`INSERT INTO inventory_movements(tenant_id,branch_id,financial_year_id,warehouse_id,item_id,movement_type,quantity,source_type,source_id,operation_key,created_by) VALUES($1,$2,$3,$4,$5,'ISSUE',$6,'MANUFACTURING_MATERIAL', $7,$8,$9)`,[i.tenantId,i.branchId,i.financialYearId,i.warehouseId,l.item_id,i.quantity,l.requisition_id,key,i.userId]);const r=await c.query('UPDATE manufacturing_material_requisition_lines SET issued_quantity=issued_quantity+$1 WHERE id=$2 AND tenant_id=$3 RETURNING *',[i.quantity,i.requisitionLineId,i.tenantId]);await c.query(`UPDATE manufacturing_material_requisitions SET status=CASE WHEN NOT EXISTS(SELECT 1 FROM manufacturing_material_requisition_lines x WHERE x.requisition_id=$1 AND x.issued_quantity<x.required_quantity) THEN 'ISSUED' ELSE 'PARTIAL' END,updated_at=now(),updated_by=$2 WHERE id=$1 AND tenant_id=$3`,[l.requisition_id,i.userId,i.tenantId]);return r.rows[0];});}

 async readinessGate(i:any){return this.tx(i.tenantId,i.userId,async c=>{const task=await c.query('SELECT t.*,ro.operation_code FROM manufacturing_task_sheets t JOIN manufacturing_routing_operations ro ON ro.id=t.routing_operation_id AND ro.tenant_id=t.tenant_id WHERE t.tenant_id=$1 AND t.id=$2 AND t.branch_id=$3',[i.tenantId,i.taskSheetId,i.branchId]);if(!task.rowCount)throw new NotFoundError('Task sheet not found.');const machine=await c.query(`SELECT * FROM manufacturing_machines WHERE tenant_id=$1 AND branch_id=$2 AND id=$3 AND is_deleted=false`,[i.tenantId,i.branchId,i.machineId]);const cap=await c.query(`SELECT * FROM manufacturing_machine_capabilities WHERE tenant_id=$1 AND branch_id=$2 AND machine_id=$3 AND operation_code=$4 AND status='ACTIVE' AND is_deleted=false`,[i.tenantId,i.branchId,i.machineId,task.rows[0].operation_code]);const tool=i.toolId?await c.query('SELECT * FROM manufacturing_tools WHERE tenant_id=$1 AND branch_id=$2 AND id=$3 AND is_deleted=false AND status=\'AVAILABLE\'',[i.tenantId,i.branchId,i.toolId]):{rowCount:1,rows:[null]};const fixture=i.fixtureId?await c.query('SELECT * FROM manufacturing_fixtures WHERE tenant_id=$1 AND branch_id=$2 AND id=$3 AND is_deleted=false AND status=\'AVAILABLE\'',[i.tenantId,i.branchId,i.fixtureId]):{rowCount:1,rows:[null]};const calibration=await c.query(`SELECT 1 FROM manufacturing_calibrations WHERE tenant_id=$1 AND branch_id=$2 AND entity_type='MACHINE' AND entity_id=$3 AND status='VALID' AND CURRENT_DATE BETWEEN valid_from AND valid_until LIMIT 1`,[i.tenantId,i.branchId,i.machineId]);const reasons=[];if(!machine.rowCount||machine.rows[0].status!=='ACTIVE')reasons.push('Machine is not active.');if(!cap.rowCount)reasons.push('Machine capability does not cover the operation.');if(!tool.rowCount)reasons.push('Required tool is not available.');if(!fixture.rowCount)reasons.push('Required fixture is not available.');if(!calibration.rowCount)reasons.push('Machine calibration is not valid.');const passed=reasons.length===0;const r=await c.query(`INSERT INTO manufacturing_readiness_checks(tenant_id,branch_id,task_sheet_id,machine_id,tool_id,fixture_id,machine_ready,tool_ready,fixture_ready,calibration_valid,passed,failure_reasons,checked_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING *`,[i.tenantId,i.branchId,i.taskSheetId,i.machineId,i.toolId??null,i.fixtureId??null,!(!machine.rowCount||machine.rows[0].status!=='ACTIVE'),!!tool.rowCount,!!fixture.rowCount,!!calibration.rowCount,passed,reasons,i.userId]);if(passed)await c.query('UPDATE manufacturing_task_sheets SET machine_id=$1,status=\'READY\',updated_at=now(),version=version+1 WHERE id=$2 AND tenant_id=$3',[i.machineId,i.taskSheetId,i.tenantId]);return {...r.rows[0],passed,failureReasons:reasons};});}

 async punchProduction(i:any){return this.tx(i.tenantId,i.userId,async c=>{const ex=await c.query('SELECT * FROM manufacturing_production_outputs WHERE tenant_id=$1 AND operation_key=$2',[i.tenantId,i.operationKey]);if(ex.rowCount)return ex.rows[0];const task=await c.query('SELECT * FROM manufacturing_task_sheets WHERE tenant_id=$1 AND branch_id=$2 AND id=$3 FOR UPDATE',[i.tenantId,i.branchId,i.taskSheetId]);if(!task.rowCount)throw new NotFoundError('Task sheet not found.');const ready=await c.query('SELECT 1 FROM manufacturing_readiness_checks WHERE tenant_id=$1 AND task_sheet_id=$2 AND passed=true ORDER BY checked_at DESC LIMIT 1',[i.tenantId,i.taskSheetId]);if(!ready.rowCount)throw new ConflictError('Machine and tooling readiness gate has not passed.');const total=await c.query('SELECT COALESCE(sum(quantity),0)::numeric total FROM manufacturing_production_outputs WHERE tenant_id=$1 AND task_sheet_id=$2',[i.tenantId,i.taskSheetId]);if(Number(total.rows[0].total)+Number(i.quantity)>Number(task.rows[0].planned_quantity))throw new ConflictError('Production output exceeds task planned quantity.');const r=await c.query(`INSERT INTO manufacturing_production_outputs(tenant_id,branch_id,task_sheet_id,quantity,output_type,heat_lot_id,serial_start,serial_end,process_parameters,punched_by,operation_key) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[i.tenantId,i.branchId,i.taskSheetId,i.quantity,i.outputType,i.heatLotId??null,i.serialStart??null,i.serialEnd??null,JSON.stringify(i.processParameters??{}),i.userId,i.operationKey]);const sums=await c.query(`SELECT COALESCE(sum(quantity) FILTER(WHERE output_type='GOOD'),0) good,COALESCE(sum(quantity) FILTER(WHERE output_type='REWORK'),0) rework,COALESCE(sum(quantity) FILTER(WHERE output_type='REJECT'),0) reject,COALESCE(sum(quantity) FILTER(WHERE output_type='RETURN'),0) return FROM manufacturing_production_outputs WHERE tenant_id=$1 AND task_sheet_id=$2`,[i.tenantId,i.taskSheetId]);await c.query('UPDATE manufacturing_task_sheets SET good_quantity=$1,rework_quantity=$2,reject_quantity=$3,return_quantity=$4,status=CASE WHEN $1+$2+$3+$4>=planned_quantity THEN \'COMPLETED\' ELSE \'RUNNING\' END,updated_at=now(),version=version+1 WHERE id=$5 AND tenant_id=$6',[sums.rows[0].good,sums.rows[0].rework,sums.rows[0].reject,sums.rows[0].return,i.taskSheetId,i.tenantId]);return r.rows[0];});}

 async punchQuality(i:any){return this.tx(i.tenantId,i.userId,async c=>{const task=await c.query('SELECT * FROM manufacturing_task_sheets WHERE tenant_id=$1 AND branch_id=$2 AND id=$3',[i.tenantId,i.branchId,i.taskSheetId]);if(!task.rowCount)throw new NotFoundError('Task sheet not found.');const produced=await c.query('SELECT COALESCE(sum(quantity),0)::numeric total FROM manufacturing_production_outputs WHERE tenant_id=$1 AND task_sheet_id=$2',[i.tenantId,i.taskSheetId]);const inspected=await c.query('SELECT COALESCE(sum(inspected_quantity),0)::numeric total FROM manufacturing_quality_outputs WHERE tenant_id=$1 AND task_sheet_id=$2',[i.tenantId,i.taskSheetId]);if(Number(inspected.rows[0].total)+Number(i.inspectedQuantity)>Number(produced.rows[0].total))throw new ConflictError('Inspected quantity exceeds production output.');if(Number(i.inspectedQuantity)!==Number(i.acceptedQuantity)+Number(i.rejectedQuantity)+Number(i.reworkQuantity)+Number(i.returnedQuantity))throw new ValidationError('Inspected Qty must equal Accepted + Rejected + Rework + Return.');const disposition=i.rejectedQuantity>0&&i.acceptedQuantity>0?'MIXED':i.rejectedQuantity>0?'REJECTED':i.reworkQuantity>0?'REWORK':i.returnedQuantity>0?'RETURNED':'ACCEPTED';const r=await c.query(`INSERT INTO manufacturing_quality_outputs(tenant_id,branch_id,task_sheet_id,inspected_quantity,accepted_quantity,rejected_quantity,rework_quantity,returned_quantity,defect_code,root_cause,disposition,inspected_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[i.tenantId,i.branchId,i.taskSheetId,i.inspectedQuantity,i.acceptedQuantity,i.rejectedQuantity,i.reworkQuantity,i.returnedQuantity,i.defectCode??null,i.rootCause??null,disposition,i.userId]);return r.rows[0];});}

 async createMaterialReturn(i:any){return this.tx(i.tenantId,i.userId,async c=>{const ex=await c.query('SELECT * FROM manufacturing_material_returns WHERE tenant_id=$1 AND operation_key=$2',[i.tenantId,i.operationKey]);if(ex.rowCount)return ex.rows[0];await c.query(`INSERT INTO inventory_movements(tenant_id,branch_id,financial_year_id,warehouse_id,item_id,movement_type,quantity,source_type,source_id,operation_key,created_by) VALUES($1,$2,$3,$4,$5,'RETURN',$6,'MANUFACTURING_MATERIAL_RETURN',$7,$8,$9)`,[i.tenantId,i.branchId,i.financialYearId,i.warehouseId,i.itemId,i.quantity,i.workOrderId,i.operationKey,i.userId]);await c.query(`INSERT INTO inventory_stock(tenant_id,warehouse_id,item_id,on_hand_quantity,reserved_quantity,created_by,updated_by) VALUES($1,$2,$3,$4,0,$5,$5) ON CONFLICT(tenant_id,warehouse_id,item_id) DO UPDATE SET on_hand_quantity=inventory_stock.on_hand_quantity+EXCLUDED.on_hand_quantity,version=inventory_stock.version+1,updated_at=now(),updated_by=$5`,[i.tenantId,i.warehouseId,i.itemId,i.quantity,i.userId]);const r=await c.query(`INSERT INTO manufacturing_material_returns(tenant_id,branch_id,work_order_id,warehouse_id,item_id,quantity,heat_lot_id,reason,return_number,operation_key,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[i.tenantId,i.branchId,i.workOrderId,i.warehouseId,i.itemId,i.quantity,i.heatLotId??null,i.reason??null,i.returnNumber,i.operationKey,i.userId]);return r.rows[0];});}

 async createVariance(i:any){return this.tx(i.tenantId,i.userId,async c=>{const total=Number(i.quantity)*Number(i.unitCost);const r=await c.query(`INSERT INTO manufacturing_variance_costs(tenant_id,branch_id,work_order_id,task_sheet_id,variance_type,quantity,unit_cost,total_cost,reason,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[i.tenantId,i.branchId,i.workOrderId,i.taskSheetId??null,i.varianceType,i.quantity,i.unitCost,total,i.reason??null,i.userId]);return r.rows[0];});}
}
