import type { Pool } from 'pg';
import type { PriceListItemRecord, PriceListRecord, PriceListRepository } from '../../../domain/contracts/pricing.js';
import { withTenantContext } from '../tenant-context.js';
import { ValidationError } from '../../../domain/errors.js';
const C=`id,tenant_id AS "tenantId",organization_id AS "organizationId",branch_id AS "branchId",code,name,currency,effective_from AS "effectiveFrom",effective_to AS "effectiveTo",status,version_number AS "versionNumber",created_at AS "createdAt",updated_at AS "updatedAt"`;
const I=`id,price_list_id AS "priceListId",item_code AS "itemCode",unit_of_measure AS "unitOfMeasure",price,effective_from AS "effectiveFrom",effective_to AS "effectiveTo",version_number AS "versionNumber"`;
export class PostgresPricingRepository implements PriceListRepository {
 constructor(private readonly pool:Pool,private readonly key='app.current_tenant_id'){}
 async create(i:any){return withTenantContext(this.pool,this.key,i.tenantId,async c=>(await c.query(`INSERT INTO sales_price_lists(tenant_id,organization_id,branch_id,code,name,currency,effective_from,effective_to,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING ${C}`,[i.tenantId,i.organizationId,i.branchId,i.code,i.name,i.currency,i.effectiveFrom,i.effectiveTo,i.actorUserId])).rows[0],{organizationId:i.organizationId,userId:i.actorUserId}) as Promise<PriceListRecord>;}
 async getById(t:string,o:string,id:string){return withTenantContext(this.pool,this.key,t,async c=>{const row=(await c.query(`SELECT ${C} FROM sales_price_lists WHERE tenant_id=$1 AND organization_id=$2 AND id=$3`,[t,o,id])).rows[0];if(!row)return null;row.items=(await c.query(`SELECT ${I} FROM sales_price_list_items WHERE tenant_id=$1 AND organization_id=$2 AND price_list_id=$3 ORDER BY item_code`,[t,o,id])).rows;return row;},{organizationId:o}) as Promise<PriceListRecord|null>;}
 async list(t:string,o:string){return withTenantContext(this.pool,this.key,t,async c=>{const rows=(await c.query(`SELECT ${C} FROM sales_price_lists WHERE tenant_id=$1 AND organization_id=$2 ORDER BY code`,[t,o])).rows;for(const row of rows)row.items=(await c.query(`SELECT ${I} FROM sales_price_list_items WHERE tenant_id=$1 AND organization_id=$2 AND price_list_id=$3 ORDER BY item_code`,[t,o,row.id])).rows;return rows;},{organizationId:o}) as Promise<PriceListRecord[]>;}
 async addItem(i:any){return withTenantContext(this.pool,this.key,i.tenantId,async c=>{await c.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[`${i.priceListId}:${i.itemCode}:${i.unitOfMeasure}`]);const overlap=await c.query(`SELECT 1 FROM sales_price_list_items WHERE tenant_id=$1 AND organization_id=$2 AND price_list_id=$3 AND item_code=$4 AND unit_of_measure=$5 AND daterange(effective_from,COALESCE(effective_to + 1,'infinity'::date),'[]') && daterange($6::date,COALESCE($7::date + 1,'infinity'::date),'[]') LIMIT 1`,[i.tenantId,i.organizationId,i.priceListId,i.itemCode,i.unitOfMeasure,i.effectiveFrom,i.effectiveTo??null]);if(overlap.rowCount)throw new ValidationError('Overlapping effective price period exists.');const row=(await c.query(`INSERT INTO sales_price_list_items(tenant_id,organization_id,price_list_id,item_code,unit_of_measure,price,effective_from,effective_to,created_by) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9 WHERE EXISTS(SELECT 1 FROM sales_price_lists WHERE id=$3 AND tenant_id=$1 AND organization_id=$2 AND status='DRAFT') RETURNING ${I}`,[i.tenantId,i.organizationId,i.priceListId,i.itemCode,i.unitOfMeasure,i.price,i.effectiveFrom,i.effectiveTo??null,i.actorUserId])).rows[0];if(!row)throw new ValidationError('Draft price list not found.');return {...row,price:Number(row.price)};},{organizationId:i.organizationId,userId:i.actorUserId}) as Promise<PriceListItemRecord>;}
 async resolvePrice(i:any){return withTenantContext(this.pool,this.key,i.tenantId,async c=>{const row=(await c.query(`SELECT i.id,i.price_list_id AS "priceListId",i.item_code AS "itemCode",i.unit_of_measure AS "unitOfMeasure",i.price,i.effective_from AS "effectiveFrom",i.effective_to AS "effectiveTo",i.version_number AS "versionNumber" FROM sales_price_list_items i JOIN sales_price_lists l ON l.id=i.price_list_id AND l.tenant_id=i.tenant_id WHERE i.tenant_id=$1 AND i.organization_id=$2 AND i.item_code=$3 AND i.unit_of_measure=$4 AND l.status='PUBLISHED' AND i.effective_from<= $5::date AND (i.effective_to IS NULL OR i.effective_to>=$5::date) AND l.effective_from<= $5::date AND (l.effective_to IS NULL OR l.effective_to>=$5::date) AND (l.branch_id=$6 OR l.branch_id IS NULL) ORDER BY (l.branch_id IS NULL),l.effective_from DESC,i.effective_from DESC`,[i.tenantId,i.organizationId,i.itemCode,i.unitOfMeasure,i.asOf,i.branchId])).rows[0];return row?{...row,price:Number(row.price)}:null;},{organizationId:i.organizationId}) as Promise<PriceListItemRecord|null>;}
 async update(i:any){return withTenantContext(this.pool,this.key,i.tenantId,async c=>(await c.query(`UPDATE sales_price_lists SET name=$1,effective_to=$2,updated_at=now(),updated_by=$3,version_number=version_number+1 WHERE tenant_id=$4 AND organization_id=$5 AND id=$6 AND status='DRAFT' AND version_number=$7 RETURNING ${C}`,[i.name,i.effectiveTo,i.actorUserId,i.tenantId,i.organizationId,i.id,i.expectedVersion])).rows[0]??null,{organizationId:i.organizationId,userId:i.actorUserId}) as Promise<PriceListRecord|null>;}
 async transition(i:any){return withTenantContext(this.pool,this.key,i.tenantId,async c=>(await c.query(`UPDATE sales_price_lists SET status=$1::sales_price_list_status_enum,updated_at=now(),updated_by=$2,version_number=version_number+1 WHERE tenant_id=$3 AND organization_id=$4 AND id=$5 AND version_number=$6 AND ((status='DRAFT' AND $1='PUBLISHED') OR (status='PUBLISHED' AND $1='ARCHIVED') ) RETURNING ${C}`,[i.status,i.actorUserId,i.tenantId,i.organizationId,i.id,i.expectedVersion])).rows[0]??null,{organizationId:i.organizationId,userId:i.actorUserId}) as Promise<PriceListRecord|null>;}
}
