import type { Pool } from 'pg';
import type { PriceListRecord, PriceListRepository } from '../../../domain/contracts/pricing.js';
import { withTenantContext } from '../tenant-context.js';
const C=`id,tenant_id AS "tenantId",organization_id AS "organizationId",branch_id AS "branchId",code,name,currency,effective_from AS "effectiveFrom",effective_to AS "effectiveTo",status,version_number AS "versionNumber",created_at AS "createdAt",updated_at AS "updatedAt"`;
export class PostgresPricingRepository implements PriceListRepository {
 constructor(private readonly pool:Pool,private readonly key='app.current_tenant_id'){}
 async create(i:any){return withTenantContext(this.pool,this.key,i.tenantId,async c=>(await c.query(`INSERT INTO sales_price_lists(tenant_id,organization_id,branch_id,code,name,currency,effective_from,effective_to,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING ${C}`,[i.tenantId,i.organizationId,i.branchId,i.code,i.name,i.currency,i.effectiveFrom,i.effectiveTo,i.actorUserId])).rows[0],{organizationId:i.organizationId,userId:i.actorUserId}) as Promise<PriceListRecord>;}
 async getById(t:string,o:string,id:string){return withTenantContext(this.pool,this.key,t,async c=>(await c.query(`SELECT ${C} FROM sales_price_lists WHERE tenant_id=$1 AND organization_id=$2 AND id=$3`,[t,o,id])).rows[0]??null,{organizationId:o}) as Promise<PriceListRecord|null>;}
 async list(t:string,o:string){return withTenantContext(this.pool,this.key,t,async c=>(await c.query(`SELECT ${C} FROM sales_price_lists WHERE tenant_id=$1 AND organization_id=$2 ORDER BY code`,[t,o])).rows,{organizationId:o}) as Promise<PriceListRecord[]>;}
 async update(i:any){return withTenantContext(this.pool,this.key,i.tenantId,async c=>(await c.query(`UPDATE sales_price_lists SET name=$1,effective_to=$2,updated_at=now(),updated_by=$3,version_number=version_number+1 WHERE tenant_id=$4 AND organization_id=$5 AND id=$6 AND status='DRAFT' AND version_number=$7 RETURNING ${C}`,[i.name,i.effectiveTo,i.actorUserId,i.tenantId,i.organizationId,i.id,i.expectedVersion])).rows[0]??null,{organizationId:i.organizationId,userId:i.actorUserId}) as Promise<PriceListRecord|null>;}
 async transition(i:any){return withTenantContext(this.pool,this.key,i.tenantId,async c=>(await c.query(`UPDATE sales_price_lists SET status=$1,updated_at=now(),updated_by=$2,version_number=version_number+1 WHERE tenant_id=$3 AND organization_id=$4 AND id=$5 AND version_number=$6 AND ((status='DRAFT' AND $1='PUBLISHED') OR (status='PUBLISHED' AND $1='ARCHIVED')) RETURNING ${C}`,[i.status,i.actorUserId,i.tenantId,i.organizationId,i.id,i.expectedVersion])).rows[0]??null,{organizationId:i.organizationId,userId:i.actorUserId}) as Promise<PriceListRecord|null>;}
}
