import type { Pool } from 'pg';
import type { DeliveryRecord, DeliveryRepository } from '../../../domain/contracts/repositories.js';
import { withTenantContext } from '../tenant-context.js';
import { ValidationError } from '../../../domain/errors.js';

const C = `id,tenant_id AS "tenantId",organization_id AS "organizationId",branch_id AS "branchId",financial_year_id AS "financialYearId",delivery_number AS "deliveryNumber",sales_order_id AS "salesOrderId",customer_id AS "customerId",status,idempotency_key AS "idempotencyKey",notes,created_at AS "createdAt",created_by AS "createdBy",updated_at AS "updatedAt",updated_by AS "updatedBy",version_number AS "versionNumber"`;
export class PostgresDeliveryRepository implements DeliveryRepository {
  constructor(private readonly pool: Pool, private readonly key = 'app.current_tenant_id') {}
  async create(i: any): Promise<DeliveryRecord> {
    return withTenantContext(this.pool, this.key, i.tenantId, async (c) => {
      const existing = await c.query(`SELECT ${C} FROM sales_deliveries WHERE tenant_id=$1 AND organization_id=$2 AND branch_id=$3 AND financial_year_id=$4 AND (idempotency_key=$5 OR sales_order_id=$6)`, [i.tenantId, i.organizationId, i.branchId, i.financialYearId, i.idempotencyKey, i.salesOrderId]);
      if (existing.rows[0]) return this.map(c, existing.rows[0]);
      const order = await c.query(`SELECT id,customer_id AS "customerId",status FROM sales_orders WHERE id=$1 AND tenant_id=$2 AND organization_id=$3 AND branch_id=$4 AND financial_year_id=$5 AND is_deleted=false`, [i.salesOrderId, i.tenantId, i.organizationId, i.branchId, i.financialYearId]);
      if (!order.rows[0] || order.rows[0].status !== 'CONFIRMED') throw new ValidationError('Only a confirmed Sales Order in the active context can create a delivery.');
      const counter = await c.query(`INSERT INTO code_counters(tenant_id,entity_type,scope_key,last_value) VALUES($1,'sales_delivery',$2,1) ON CONFLICT(tenant_id,entity_type,scope_key) DO UPDATE SET last_value=code_counters.last_value+1 RETURNING last_value`, [i.tenantId, i.organizationId]);
      const r = await c.query(`INSERT INTO sales_deliveries(tenant_id,organization_id,branch_id,financial_year_id,delivery_number,sales_order_id,customer_id,idempotency_key,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING ${C}`, [i.tenantId,i.organizationId,i.branchId,i.financialYearId,`DEL-${String(counter.rows[0].last_value).padStart(6,'0')}`,i.salesOrderId,order.rows[0].customerId,i.idempotencyKey,i.notes,i.actorUserId]);
      await c.query(`INSERT INTO sales_delivery_items(tenant_id,organization_id,branch_id,financial_year_id,delivery_id,order_item_id,line_number,description,quantity,unit_of_measure,created_by) SELECT tenant_id,organization_id,branch_id,financial_year_id,$1,id,line_number,description,quantity,unit_of_measure,$2 FROM sales_order_items WHERE order_id=$3 AND tenant_id=$4`, [r.rows[0].id,i.actorUserId,i.salesOrderId,i.tenantId]);
      return this.map(c, r.rows[0]);
    }, { organizationId: i.organizationId, userId: i.actorUserId }) as Promise<DeliveryRecord>;
  }
  async getById(t: string,o: string,b: string,fy: string,id: string) { return withTenantContext(this.pool,this.key,t,(c)=>this.getOn(c,t,o,b,fy,id),{organizationId:o}); }
  async list(t: string,q: any) { return withTenantContext(this.pool,this.key,t,async(c)=>{const v:any[]=[t,q.organizationId,q.branchId,q.financialYearId],f=['tenant_id=$1','organization_id=$2','branch_id=$3','financial_year_id=$4'];if(q.search){v.push(`%${q.search}%`);f.push(`(delivery_number ILIKE $${v.length} OR status::text ILIKE $${v.length})`);}const count=await c.query(`SELECT count(*)::int count FROM sales_deliveries WHERE ${f.join(' AND ')}`,v);v.push((q.page-1)*q.pageSize,q.pageSize);const d=q.order==='desc'?'DESC':'ASC';const rows=await c.query(`SELECT ${C} FROM sales_deliveries WHERE ${f.join(' AND ')} ORDER BY delivery_number ${d},id ${d} OFFSET $${v.length-1} LIMIT $${v.length}`,v);return {items:await Promise.all(rows.rows.map((r:any)=>this.map(c,r))),total:Number(count.rows[0].count)};},{organizationId:q.organizationId});}
  async update(i:any){return this.mutate(i,`UPDATE sales_deliveries SET notes=$1,updated_at=now(),updated_by=$2,version_number=version_number+1 WHERE tenant_id=$3 AND organization_id=$4 AND branch_id=$5 AND financial_year_id=$6 AND id=$7 AND status='DRAFT' AND version_number=$8 RETURNING ${C}`,[i.notes,i.actorUserId,i.tenantId,i.organizationId,i.branchId,i.financialYearId,i.deliveryId,i.expectedVersion]);}
  async transition(i:any){return this.mutate(i,`UPDATE sales_deliveries SET status=$1,updated_at=now(),updated_by=$2,version_number=version_number+1 WHERE tenant_id=$3 AND organization_id=$4 AND branch_id=$5 AND financial_year_id=$6 AND id=$7 AND version_number=$8 RETURNING ${C}`,[i.status,i.actorUserId,i.tenantId,i.organizationId,i.branchId,i.financialYearId,i.deliveryId,i.expectedVersion]);}
  private async mutate(i:any,sql:string,v:any[]){return withTenantContext(this.pool,this.key,i.tenantId,async(c)=>{const r=await c.query(sql,v);return r.rows[0]?this.map(c,r.rows[0]):null;},{organizationId:i.organizationId,userId:i.actorUserId});}
  private async getOn(c:any,t:string,o:string,b:string,fy:string,id:string){const r=await c.query(`SELECT ${C} FROM sales_deliveries WHERE tenant_id=$1 AND organization_id=$2 AND branch_id=$3 AND financial_year_id=$4 AND id=$5`,[t,o,b,fy,id]);return r.rows[0]?this.map(c,r.rows[0]):null;}
  private async map(c:any,r:any):Promise<DeliveryRecord>{const x=await c.query(`SELECT id,line_number AS "lineNumber",order_item_id AS "orderItemId",description,quantity,unit_of_measure AS "unitOfMeasure" FROM sales_delivery_items WHERE delivery_id=$1 AND tenant_id=$2 ORDER BY line_number`,[r.id,r.tenantId]);return {...r,items:x.rows.map((a:any)=>({...a,quantity:Number(a.quantity)})),createdAt:new Date(r.createdAt),updatedAt:r.updatedAt?new Date(r.updatedAt):null};}
}
