import type { Pool } from 'pg';
import type { SalesReturnRecord, SalesReturnRepository } from '../../../domain/contracts/repositories.js';
import { withTenantContext } from '../tenant-context.js';
import { ValidationError } from '../../../domain/errors.js';
const C=`id,tenant_id AS "tenantId",organization_id AS "organizationId",branch_id AS "branchId",financial_year_id AS "financialYearId",return_number AS "returnNumber",invoice_id AS "invoiceId",delivery_id AS "deliveryId",customer_id AS "customerId",status,idempotency_key AS "idempotencyKey",inventory_status AS "inventoryStatus",finance_status AS "financeStatus",notes,created_at AS "createdAt",created_by AS "createdBy",updated_at AS "updatedAt",updated_by AS "updatedBy",version_number AS "versionNumber"`;
export class PostgresSalesReturnRepository implements SalesReturnRepository {
  constructor(private readonly pool:Pool,private readonly key='app.current_tenant_id'){}
  async create(i:any):Promise<SalesReturnRecord>{return withTenantContext(this.pool,this.key,i.tenantId,async(c)=>{const e=await c.query(`SELECT ${C} FROM sales_returns WHERE tenant_id=$1 AND organization_id=$2 AND branch_id=$3 AND financial_year_id=$4 AND (idempotency_key=$5 OR invoice_id=$6)`,[i.tenantId,i.organizationId,i.branchId,i.financialYearId,i.idempotencyKey,i.invoiceId]);if(e.rows[0])return this.map(c,e.rows[0]);const inv=await c.query(`SELECT id,delivery_id AS "deliveryId",customer_id AS "customerId",status FROM sales_invoices WHERE id=$1 AND tenant_id=$2 AND organization_id=$3 AND branch_id=$4 AND financial_year_id=$5`,[i.invoiceId,i.tenantId,i.organizationId,i.branchId,i.financialYearId]);if(!inv.rows[0]||inv.rows[0].status!=='ISSUED')throw new ValidationError('Only an issued invoice in the active context can create a Sales Return.');const d=await c.query(`SELECT sales_order_id AS "salesOrderId" FROM sales_deliveries WHERE id=$1 AND tenant_id=$2`,[inv.rows[0].deliveryId]);const n=await c.query(`INSERT INTO code_counters(tenant_id,entity_type,scope_key,last_value) VALUES($1,'sales_return',$2,1) ON CONFLICT(tenant_id,entity_type,scope_key) DO UPDATE SET last_value=code_counters.last_value+1 RETURNING last_value`,[i.tenantId,i.organizationId]);const r=await c.query(`INSERT INTO sales_returns(tenant_id,organization_id,branch_id,financial_year_id,return_number,invoice_id,delivery_id,customer_id,idempotency_key,notes,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING ${C}`,[i.tenantId,i.organizationId,i.branchId,i.financialYearId,`RET-${String(n.rows[0].last_value).padStart(6,'0')}`,i.invoiceId,inv.rows[0].deliveryId,inv.rows[0].customerId,i.idempotencyKey,i.notes,i.actorUserId]);await c.query(`INSERT INTO sales_return_items(tenant_id,organization_id,branch_id,financial_year_id,return_id,invoice_item_id,line_number,description,quantity,unit_price,unit_of_measure,created_by) SELECT tenant_id,organization_id,branch_id,financial_year_id,$1,id,line_number,description,quantity,unit_price,unit_of_measure,$2 FROM sales_invoice_items WHERE invoice_id=$3 AND tenant_id=$4`,[r.rows[0].id,i.actorUserId,i.invoiceId,i.tenantId]);void d;return this.map(c,r.rows[0]);},{organizationId:i.organizationId,userId:i.actorUserId}) as Promise<SalesReturnRecord>;}
  async getById(t:string,o:string,b:string,fy:string,id:string){return withTenantContext(this.pool,this.key,t,(c)=>this.getOn(c,t,o,b,fy,id),{organizationId:o});}
  async list(t:string,q:any){return withTenantContext(this.pool,this.key,t,async(c)=>{const v:any[]=[t,q.organizationId,q.branchId,q.financialYearId],f=['tenant_id=$1','organization_id=$2','branch_id=$3','financial_year_id=$4'];if(q.search){v.push(`%${q.search}%`);f.push(`(return_number ILIKE $${v.length} OR status::text ILIKE $${v.length})`);}const count=await c.query(`SELECT count(*)::int count FROM sales_returns WHERE ${f.join(' AND ')}`,v);v.push((q.page-1)*q.pageSize,q.pageSize);const d=q.order==='desc'?'DESC':'ASC';const rows=await c.query(`SELECT ${C} FROM sales_returns WHERE ${f.join(' AND ')} ORDER BY return_number ${d},id ${d} OFFSET $${v.length-1} LIMIT $${v.length}`,v);return{items:await Promise.all(rows.rows.map((r:any)=>this.map(c,r))),total:Number(count.rows[0].count)};},{organizationId:q.organizationId});}
  async update(i:any){return this.mutate(i,`UPDATE sales_returns SET notes=$1,updated_at=now(),updated_by=$2,version_number=version_number+1 WHERE tenant_id=$3 AND organization_id=$4 AND branch_id=$5 AND financial_year_id=$6 AND id=$7 AND status='REQUESTED' AND version_number=$8 RETURNING ${C}`,[i.notes,i.actorUserId,i.tenantId,i.organizationId,i.branchId,i.financialYearId,i.returnId,i.expectedVersion]);}
  async transition(i:any){return this.mutate(i,`UPDATE sales_returns SET status=$1,updated_at=now(),updated_by=$2,version_number=version_number+1 WHERE tenant_id=$3 AND organization_id=$4 AND branch_id=$5 AND financial_year_id=$6 AND id=$7 AND version_number=$8 RETURNING ${C}`,[i.status,i.actorUserId,i.tenantId,i.organizationId,i.branchId,i.financialYearId,i.returnId,i.expectedVersion]);}
  private async mutate(i:any,s:string,v:any[]){return withTenantContext(this.pool,this.key,i.tenantId,async(c)=>{const r=await c.query(s,v);return r.rows[0]?this.map(c,r.rows[0]):null;},{organizationId:i.organizationId,userId:i.actorUserId});}
  private async getOn(c:any,t:string,o:string,b:string,fy:string,id:string){const r=await c.query(`SELECT ${C} FROM sales_returns WHERE tenant_id=$1 AND organization_id=$2 AND branch_id=$3 AND financial_year_id=$4 AND id=$5`,[t,o,b,fy,id]);return r.rows[0]?this.map(c,r.rows[0]):null;}
  private async map(c:any,r:any):Promise<SalesReturnRecord>{const x=await c.query(`SELECT id,line_number AS "lineNumber",invoice_item_id AS "invoiceItemId",description,quantity,unit_price AS "unitPrice",unit_of_measure AS "unitOfMeasure" FROM sales_return_items WHERE return_id=$1 AND tenant_id=$2 ORDER BY line_number`,[r.id,r.tenantId]);return{...r,items:x.rows.map((a:any)=>({...a,quantity:Number(a.quantity),unitPrice:Number(a.unitPrice)})),createdAt:new Date(r.createdAt),updatedAt:r.updatedAt?new Date(r.updatedAt):null};}
}
