import { validate as isUuid } from 'uuid';
import type { AuditLogger } from '../contracts/audit.js';
import type { AuthorizationService } from './authorization-service.js';
import type { ModuleAccessService } from './module-access-service.js';
import type { CreditNoteRecord, CreditNoteRepository } from '../../domain/contracts/repositories.js';
import { CREDIT_NOTE_PERMISSIONS, type CreditNotePermission, type CreditNoteStatus } from '../../domain/contracts/credit-note.js';
import { ForbiddenError, NotFoundError, UnauthorizedError, ValidationError } from '../../domain/errors.js';
import type { FinancePostingPort } from '../../domain/contracts/sales-dependencies.js';
export interface CreditNoteContext { tenantId:string; organizationId:string; branchId:string; financialYearId:string; userId:string; }
export interface CreditNoteTransactionRunner { runInTransaction<T>(callback:()=>Promise<T>):Promise<T>; }
const transitions:Record<CreditNoteStatus,CreditNoteStatus[]>={DRAFT:['ISSUED','CANCELLED'],ISSUED:[],CANCELLED:[]};
export class CreditNoteService{
constructor(private readonly repository:CreditNoteRepository,private readonly auth:Pick<AuthorizationService,'hasPermission'>,private readonly modules:Pick<ModuleAccessService,'isModuleEnabled'>,private readonly audit:AuditLogger,private readonly tx:CreditNoteTransactionRunner,private readonly finance?: FinancePostingPort){}
async create(c:CreditNoteContext,input:{returnId:string;idempotencyKey:string;notes?:string|null}):Promise<CreditNoteRecord>{await this.authorize(c,CREDIT_NOTE_PERMISSIONS.create);this.id(input.returnId,'Return ID');const k=input.idempotencyKey?.trim();if(!k||k.length>128)throw new ValidationError('Idempotency key is required and must be at most 128 characters.');const allowReplay=await this.auth.hasPermission(c.tenantId,c.userId,CREDIT_NOTE_PERMISSIONS.read);return this.tx.runInTransaction(async()=>{const v=await this.repository.create({...c,returnId:input.returnId,idempotencyKey:k,notes:input.notes??null,actorUserId:c.userId,allowReplay});await this.audit.record({tenantId:c.tenantId,actorUserId:c.userId,action:'credit_note.created',resourceType:'sales_credit_note',resourceId:v.id,outcome:'success'},{requireTransaction:true});return v;});}
async get(c:CreditNoteContext,id:string){await this.authorize(c,CREDIT_NOTE_PERMISSIONS.read);this.id(id,'Credit Note ID');const v=await this.repository.getById(c.tenantId,c.organizationId,c.branchId,c.financialYearId,id);if(!v)throw new NotFoundError('Credit Note not found.');return v;}
async list(c:CreditNoteContext,input:{page:number;pageSize:number;order:'asc'|'desc';search?:string}){await this.authorize(c,CREDIT_NOTE_PERMISSIONS.read);return this.repository.list(c.tenantId,{...input,organizationId:c.organizationId,branchId:c.branchId,financialYearId:c.financialYearId});}
async update(c:CreditNoteContext,id:string,input:{notes?:string|null;expectedVersion:number}){await this.authorize(c,CREDIT_NOTE_PERMISSIONS.update);this.id(id,'Credit Note ID');this.version(input.expectedVersion);const v=await this.repository.update({...c,creditNoteId:id,notes:input.notes??null,expectedVersion:input.expectedVersion,actorUserId:c.userId});if(!v)throw new ValidationError('Draft credit note not found or version conflict.');return v;}
async transition(c:CreditNoteContext,id:string,status:CreditNoteStatus,expectedVersion:number){await this.authorize(c,status==='ISSUED'?CREDIT_NOTE_PERMISSIONS.issue:CREDIT_NOTE_PERMISSIONS.cancel);this.id(id,'Credit Note ID');this.version(expectedVersion);return this.tx.runInTransaction(async()=>{const current=await this.get(c,id);if(!transitions[current.status].includes(status))throw new ValidationError(`Credit Note cannot transition from ${current.status} to ${status}.`);let transitionVersion=expectedVersion;if(status==='ISSUED'){if(!this.finance||!this.repository.updateFinanceStatus)throw new ValidationError('Finance provider is not configured.');const amount=current.items.reduce((total,item)=>total+item.lineTotal,0);const posting=await this.finance.submitSalesDocument({...c,actorUserId:c.userId,correlationId:id,idempotencyKey:`credit-note-finance:${id}`},'CREDIT_NOTE',id,amount);if(posting.status!=='POSTED'||!posting.reference)throw new ValidationError('Finance credit adjustment failed.');const posted=await this.repository.updateFinanceStatus({...c,creditNoteId:id,financeReference:posting.reference,actorUserId:c.userId});if(!posted)throw new ValidationError('Credit Note finance status could not be persisted.');transitionVersion++;}const v=await this.repository.transition({...c,creditNoteId:id,status,expectedVersion:transitionVersion,actorUserId:c.userId});if(!v)throw new ValidationError('Credit Note not found or version conflict.');await this.audit.record({tenantId:c.tenantId,actorUserId:c.userId,action:`credit_note.${status.toLowerCase()}`,resourceType:'sales_credit_note',resourceId:id,outcome:'success'},{requireTransaction:true});return v;});}
private async authorize(c:CreditNoteContext,p:CreditNotePermission){if(!c.userId?.trim())throw new UnauthorizedError();for(const[v,l]of[[c.tenantId,'Tenant ID'],[c.organizationId,'Organization ID'],[c.branchId,'Branch ID'],[c.financialYearId,'Financial Year ID'],[c.userId,'User ID']]as const)this.id(v,l);if(!(await this.modules.isModuleEnabled(c.tenantId,c.organizationId,'sales')))throw new ForbiddenError('Sales module is not enabled.');if(!(await this.auth.hasPermission(c.tenantId,c.userId,p)))throw new ForbiddenError('Insufficient Credit Note permission.');}
private id(v:string,l:string){if(!v||!isUuid(v))throw new ValidationError(`${l} must be a valid UUID.`);}private version(v:number){if(!Number.isInteger(v)||v<1)throw new ValidationError('Expected version must be a positive integer.');}}
