import {validate as isUuid} from 'uuid';import type {AuditLogger} from '../contracts/audit.js';import type {AuthorizationService} from './authorization-service.js';import type {ModuleAccessService} from './module-access-service.js';import type {DiscountRuleRecord,DiscountRuleRepository,DiscountStatus,ResolvedDiscountRule} from '../../domain/contracts/discount.js';import{ForbiddenError,UnauthorizedError,ValidationError}from '../../domain/errors.js';
export interface DiscountContext{tenantId:string;organizationId:string;branchId?:string;userId:string}
export class DiscountService{constructor(private readonly r:DiscountRuleRepository,private readonly a:Pick<AuthorizationService,'hasPermission'>,private readonly m:Pick<ModuleAccessService,'isModuleEnabled'>,private readonly audit:AuditLogger){}
async create(c:DiscountContext,i:{code:string;name:string;percentage:number;effectiveFrom:string;effectiveTo?:string|null}):Promise<DiscountRuleRecord>{await this.auth(c,'sales.discount.create');if(!i.code?.trim()||!i.name?.trim()||!Number.isFinite(i.percentage)||i.percentage<=0||i.percentage>100)throw new ValidationError('Code, name, and percentage between 0 and 100 are required.');const x=await this.r.create({...c,...i,effectiveTo:i.effectiveTo??null,actorUserId:c.userId});await this.audit.record({tenantId:c.tenantId,actorUserId:c.userId,action:'discount.created',resourceType:'sales_discount_rule',resourceId:x.id,outcome:'success'});return x;}
async list(c:DiscountContext){await this.auth(c,'sales.discount.read');return this.r.list(c.tenantId,c.organizationId);}
async get(c:DiscountContext,id:string){await this.auth(c,'sales.discount.read');this.id(id);const x=await this.r.get(c.tenantId,c.organizationId,id);if(!x)throw new ValidationError('Discount rule not found.');return x;}
async update(c:DiscountContext,id:string,i:{name:string;percentage:number;effectiveFrom:string;effectiveTo?:string|null;expectedVersion:number}):Promise<DiscountRuleRecord>{await this.auth(c,'sales.discount.update');this.id(id);if(!i.name?.trim()||!Number.isFinite(i.percentage)||i.percentage<=0||i.percentage>100||!i.effectiveFrom||(i.effectiveTo!==undefined&&i.effectiveTo!==null&&i.effectiveTo<i.effectiveFrom))throw new ValidationError('Name, percentage, and a valid effective period are required.');const x=await this.r.update({...c,id,name:i.name.trim(),percentage:i.percentage,effectiveFrom:i.effectiveFrom,effectiveTo:i.effectiveTo??null,expectedVersion:i.expectedVersion,actorUserId:c.userId});if(!x)throw new ValidationError('Draft discount rule not found or version conflict.');await this.audit.record({tenantId:c.tenantId,actorUserId:c.userId,action:'discount.updated',resourceType:'sales_discount_rule',resourceId:id,outcome:'success'});return x;}
 async resolve(c:DiscountContext,asOf:string):Promise<ResolvedDiscountRule|null>{await this.auth(c,'sales.discount.read');if(!asOf||Number.isNaN(Date.parse(asOf)))throw new ValidationError('A valid effective date is required.');return this.r.resolve(c.tenantId,c.organizationId,asOf);}
async transition(c:DiscountContext,id:string,status:DiscountStatus,expectedVersion:number){await this.auth(c,`sales.discount.${status==='PUBLISHED'?'publish':'archive'}`);this.id(id);const x=await this.r.transition({...c,id,status,expectedVersion,actorUserId:c.userId});if(!x)throw new ValidationError('Discount transition failed or version conflict.');await this.audit.record({tenantId:c.tenantId,actorUserId:c.userId,action:`discount.${status.toLowerCase()}`,resourceType:'sales_discount_rule',resourceId:id,outcome:'success'});return x;}
private async auth(c:DiscountContext,p:string){if(!c.userId)throw new UnauthorizedError();for(const v of[c.tenantId,c.organizationId,c.userId])this.id(v);if(!(await this.m.isModuleEnabled(c.tenantId,c.organizationId,'sales')))throw new ForbiddenError('Sales module is not enabled.');if(!(await this.a.hasPermission(c.tenantId,c.userId,p)))throw new ForbiddenError('Insufficient discount permission.');}private id(v:string){if(!isUuid(v))throw new ValidationError('Context identifier must be a valid UUID.');}}
