import { validate as isUuid, v7 as uuidV7 } from 'uuid';
import type { Pool } from 'pg';
import { ForbiddenError, NotFoundError, ValidationError } from '../../domain/errors.js';
import type { AuthorizationService } from './authorization-service.js';
import type { ModuleAccessService } from './module-access-service.js';
import type { WorkflowService } from './workflow-service.js';
import { withTenantContext } from '../../infrastructure/database/tenant-context.js';

export interface HrContext { tenantId: string; branchId?: string | null; userId: string; }
const TABLES: Record<string,string> = {
 employees:'hr_employees',departments:'hr_departments',positions:'hr_positions',businessUnits:'hr_business_units',divisions:'hr_divisions',sections:'hr_sections',teams:'hr_teams',
 shifts:'hr_shifts',employeeShifts:'hr_employee_shifts',holidays:'hr_holidays',attendance:'hr_attendance',punches:'hr_attendance_punches',attendanceCorrections:'hr_attendance_corrections',
 leaveTypes:'hr_leave_types',leavePolicies:'hr_leave_policies',leaveBalances:'hr_leave_balances',leaveTransactions:'hr_leave_transactions',leaveRequests:'hr_leave_requests',
 salaryComponents:'hr_salary_components',salaryStructures:'hr_salary_structures',employeeSalary:'hr_employee_salary',payrollPeriods:'hr_payroll_periods',payrollRuns:'hr_payroll_runs',payslips:'hr_payslips',payrollAdjustments:'hr_payroll_adjustments',payrollLoans:'hr_payroll_loans',payrollReimbursements:'hr_payroll_reimbursements',statutoryRules:'hr_statutory_rules',
 requisitions:'hr_recruitment_requisitions',candidates:'hr_candidates',applications:'hr_applications',interviews:'hr_interviews',performanceCycles:'hr_performance_cycles',performanceReviews:'hr_performance_reviews',trainingPrograms:'hr_training_programs',trainingRecords:'hr_training_records',compliance:'hr_compliance_records',employeeRequests:'hr_employee_requests',employeeSkills:'hr_employee_skills',employeeDocuments:'hr_employee_documents',employeeRelations:'hr_employee_relations',exitRecords:'hr_exit_records',onboarding:'hr_onboarding_records'
};
const RESOURCE: Record<string,string> = {}; Object.keys(TABLES).forEach(k=>RESOURCE[k]=k); Object.assign(RESOURCE,{employees:'employee',departments:'department',positions:'position',businessUnits:'business_unit',divisions:'division',sections:'section',teams:'team',shifts:'shift',employeeShifts:'employee_shift',holidays:'holiday',attendance:'attendance',punches:'punch',attendanceCorrections:'attendance_correction',leaveTypes:'leave_type',leavePolicies:'leave_policy',leaveBalances:'leave_balance',leaveTransactions:'leave_transaction',leaveRequests:'leave_request',salaryComponents:'salary_component',salaryStructures:'salary_structure',employeeSalary:'employee_salary',payrollPeriods:'payroll_period',payrollRuns:'payroll_run',payslips:'payslip',payrollAdjustments:'payroll_adjustment',payrollLoans:'payroll_loan',payrollReimbursements:'payroll_reimbursement',statutoryRules:'statutory_rule',requisitions:'recruitment_requisition',candidates:'candidate',applications:'application',interviews:'interview',performanceCycles:'performance_cycle',performanceReviews:'performance_review',trainingPrograms:'training_program',trainingRecords:'training_record',compliance:'compliance',employeeRequests:'employee_request',employeeSkills:'employee_skill',employeeDocuments:'employee_document',employeeRelations:'employee_relation',exitRecords:'exit_record',onboarding:'onboarding'});
const WORKFLOW_TYPE: Record<string,string>={leaveRequests:'HR_LEAVE_REQUEST',requisitions:'HR_RECRUITMENT_REQUISITION',payrollRuns:'HR_PAYROLL_RUN',attendanceCorrections:'HR_ATTENDANCE_CORRECTION',employeeRequests:'HR_EMPLOYEE_REQUEST',payrollReimbursements:'HR_PAYROLL_REIMBURSEMENT',payrollLoans:'HR_PAYROLL_LOAN'};

export class HrService {
 constructor(private pool:Pool,private tenantKey:string,private authorization:Pick<AuthorizationService,'hasPermission'>,private modules:Pick<ModuleAccessService,'isModuleEnabled'>,private workflow?:Pick<WorkflowService,'onDocumentSubmitted'>){}
 private async auth(c:HrContext,r:string,a:string){if(!isUuid(c.tenantId)||!isUuid(c.userId))throw new ValidationError('Valid tenant and user context is required.');if(!(await this.modules.isModuleEnabled(c.tenantId,'hr')))throw new ForbiddenError('HR module is not enabled.');if(!(await this.authorization.hasPermission(c.tenantId,c.userId,'hr.'+r+'.'+a)))throw new ForbiddenError('HR permission denied.');}
 private table(kind:string){const table=TABLES[kind],resource=RESOURCE[kind];if(!table||!resource)throw new ValidationError('Unknown HR resource.');return{table,resource};}
 async list(c:HrContext,kind:string,page=1,pageSize=20,search?:string){const {table,resource}=this.table(kind);await this.auth(c,resource,'read');if(page<1||pageSize<1||pageSize>100)throw new ValidationError('Invalid pagination.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const params:any[]=[c.tenantId];let where='tenant_id=$1';if(search){params.push('%'+search.trim()+'%');const sf=kind==='employees'?'COALESCE(employee_no,first_name,last_name,work_email,\'\')':['departments','positions','businessUnits','divisions','sections','teams','shifts','leaveTypes','leavePolicies','salaryComponents','salaryStructures','payrollPeriods','requisitions','candidates','performanceCycles','trainingPrograms','statutoryRules'].includes(kind)?'COALESCE(code,name,\'\')':'COALESCE(status,\'\')';where+=' AND '+sf+' ILIKE $2';}if(['employees','departments','positions','shifts'].includes(kind))where+=' AND COALESCE(is_deleted,false)=false';const count=(await client.query('SELECT count(*)::int AS total FROM public.'+table+' WHERE '+where,params)).rows[0].total;params.push(pageSize,(page-1)*pageSize);const rows=(await client.query('SELECT * FROM public.'+table+' WHERE '+where+' ORDER BY created_at DESC NULLS LAST LIMIT $'+(params.length-1)+' OFFSET $'+params.length,params)).rows;return{items:rows,total:Number(count)};});}
 async get(c:HrContext,kind:string,id:string){const {table,resource}=this.table(kind);if(!isUuid(id))throw new ValidationError('Invalid HR id.');await this.auth(c,resource,'read');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const q=await client.query('SELECT * FROM public.'+table+' WHERE id=$1 AND tenant_id=$2',[id,c.tenantId]);if(!q.rowCount)throw new NotFoundError('HR record not found.');return q.rows[0];});}
 async create(c:HrContext,kind:string,input:Record<string,unknown>){const {table,resource}=this.table(kind);await this.auth(c,resource,'create');const fields=Object.keys(input).filter(k=>/^[a-z_][a-z0-9_]*$/.test(k)&&!['id','tenant_id'].includes(k));if(!fields.length)throw new ValidationError('No fields supplied.');const vals=[uuidV7(),c.tenantId,...fields.map(k=>input[k])];const record=await withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>(await client.query('INSERT INTO public.'+table+' (id,tenant_id,'+fields.join(',')+') VALUES ('+vals.map((_,i)=>'$'+(i+1)).join(',')+') RETURNING *',vals)).rows[0]);return record;}
 async update(c:HrContext,kind:string,id:string,input:Record<string,unknown>){const {table,resource}=this.table(kind);if(!isUuid(id))throw new ValidationError('Invalid HR id.');await this.auth(c,resource,'update');const fields=Object.keys(input).filter(k=>/^[a-z_][a-z0-9_]*$/.test(k)&&!['id','tenant_id','created_at'].includes(k));if(!fields.length)throw new ValidationError('No fields supplied.');const vals=[...fields.map(k=>input[k]),id,c.tenantId];const sets=fields.map((k,i)=>k+'=$'+(i+1)).join(',');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const q=await client.query('UPDATE public.'+table+' SET '+sets+(['departments','positions','shifts','employees'].includes(kind)?',updated_at=NOW()':'' )+' WHERE id=$'+(vals.length-1)+' AND tenant_id=$'+vals.length+' RETURNING *',vals);if(!q.rowCount)throw new NotFoundError('HR record not found.');return q.rows[0];});}
 async remove(c:HrContext,kind:string,id:string){const {table,resource}=this.table(kind);if(!isUuid(id))throw new ValidationError('Invalid HR id.');await this.auth(c,resource,'delete');if(!['employees','departments','positions','shifts'].includes(kind))throw new ValidationError('This HR resource does not support deletion; use lifecycle/status fields.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const q=await client.query('UPDATE public.'+table+' SET is_deleted=true,deleted_at=NOW(),updated_at=NOW() WHERE id=$1 AND tenant_id=$2 RETURNING id',[id,c.tenantId]);if(!q.rowCount)throw new NotFoundError('HR record not found.');return q.rows[0];});}
 async punch(c:HrContext,employeeId:string,direction:'IN'|'OUT',punchedAt?:string){await this.auth(c,'attendance',direction==='IN'?'create':'update');if(!isUuid(employeeId))throw new ValidationError('Invalid employee id.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const at=punchedAt?new Date(punchedAt):new Date();if(Number.isNaN(at.getTime()))throw new ValidationError('Invalid timestamp.');await client.query('INSERT INTO hr_attendance_punches(id,tenant_id,employee_id,punched_at,direction,source) VALUES($1,$2,$3,$4,$5,\'MANUAL\')',[uuidV7(),c.tenantId,employeeId,at,direction]);const date=at.toISOString().slice(0,10),field=direction==='IN'?'check_in':'check_out';return(await client.query('INSERT INTO hr_attendance(id,tenant_id,employee_id,attendance_date,'+field+',status,source) VALUES($1,$2,$3,$4,$5,\'PRESENT\',\'MANUAL\') ON CONFLICT(tenant_id,employee_id,attendance_date) DO UPDATE SET '+field+'=EXCLUDED.'+field+',updated_at=NOW() RETURNING *',[uuidV7(),c.tenantId,employeeId,date,at])).rows[0];});}
 async submitForApproval(c:HrContext,kind:string,id:string,expectedVersion=1){const {table,resource}=this.table(kind);await this.auth(c,resource,'update');const workflowType=WORKFLOW_TYPE[kind];if(!workflowType)throw new ValidationError('This HR resource has no workflow configured.');if(!this.workflow)throw new ValidationError('Workflow service is not configured.');if(!isUuid(id))throw new ValidationError('Invalid HR id.');const record=await this.get(c,kind,id);const result=await this.workflow.onDocumentSubmitted(c as any,workflowType,id,expectedVersion,uuidV7());if(result.status!=='APPROVED')await withTenantContext(this.pool,this.tenantKey,c.tenantId,client=>client.query('UPDATE public.'+table+' SET status=$1 WHERE id=$2 AND tenant_id=$3',['SUBMITTED',id,c.tenantId]));return{record,result};}
 async applyWorkflowDecision(c:HrContext,documentType:string,documentId:string,status:'APPROVED'|'REJECTED'|'CORRECTION'){
  if(!isUuid(documentId))throw new ValidationError('Invalid HR document id.');
  const mapping:Record<string,string>={HR_LEAVE_REQUEST:'leaveRequests',HR_RECRUITMENT_REQUISITION:'requisitions',HR_PAYROLL_RUN:'payrollRuns',HR_ATTENDANCE_CORRECTION:'attendanceCorrections',HR_EMPLOYEE_REQUEST:'employeeRequests',HR_PAYROLL_REIMBURSEMENT:'payrollReimbursements',HR_PAYROLL_LOAN:'payrollLoans'};
  const kind=mapping[documentType]; if(!kind)throw new ValidationError('Unsupported HR workflow document.');
  const table=TABLES[kind]; const finalStatus=status==='APPROVED'?'APPROVED':status==='REJECTED'?'REJECTED':'CORRECTION';
  const updated=await withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const sql=documentType==='HR_LEAVE_REQUEST'?'UPDATE public.'+table+' SET status=$1,approved_by=$2,approved_at=NOW() WHERE id=$3 AND tenant_id=$4 RETURNING *':'UPDATE public.'+table+' SET status=$1 WHERE id=$2 AND tenant_id=$3 RETURNING *';const params=documentType==='HR_LEAVE_REQUEST'?[finalStatus,c.userId,documentId,c.tenantId]:[finalStatus,documentId,c.tenantId];const q=await client.query(sql,params);if(!q.rowCount)throw new NotFoundError('HR workflow record not found.');return q.rows[0];});
  if(documentType==='HR_LEAVE_REQUEST'&&finalStatus==='APPROVED')await this.consumeLeave(c,documentId);
  return updated;
 }
 private async consumeLeave(c:HrContext,id:string){await withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const req=(await client.query('SELECT employee_id,leave_type_id,days,EXTRACT(YEAR FROM start_date)::int year FROM hr_leave_requests WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[id,c.tenantId])).rows[0];if(!req)throw new NotFoundError('Leave request not found.');const balance=(await client.query('SELECT * FROM hr_leave_balances WHERE tenant_id=$1 AND employee_id=$2 AND leave_type_id=$3 AND year=$4 FOR UPDATE',[c.tenantId,req.employee_id,req.leave_type_id,req.year])).rows[0];if(!balance)throw new ValidationError('Leave balance is not initialized.');const available=Number(balance.opening)+Number(balance.accrued)+Number(balance.adjusted)-Number(balance.used)-Number(balance.encashed);if(available<Number(req.days))throw new ValidationError('Insufficient leave balance.');await client.query('UPDATE hr_leave_balances SET used=used+$1 WHERE id=$2',[req.days,balance.id]);await client.query('INSERT INTO hr_leave_transactions(id,tenant_id,employee_id,leave_type_id,year,transaction_type,amount,reference_id,created_by) VALUES($1,$2,$3,$4,$5,\'USAGE\',$6,$7,$8)',[uuidV7(),c.tenantId,req.employee_id,req.leave_type_id,req.year,req.days,id,c.userId]);});}
 async calculatePayroll(c:HrContext,runId:string){
  await this.auth(c,'payroll','calculate');
  if(!isUuid(runId))throw new ValidationError('Invalid payroll run id.');
  return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{
   const run=(await client.query('SELECT r.*,p.period_start,p.period_end FROM hr_payroll_runs r JOIN hr_payroll_periods p ON p.id=r.payroll_period_id WHERE r.id=$1 AND r.tenant_id=$2 FOR UPDATE',[runId,c.tenantId])).rows[0];
   if(!run)throw new NotFoundError('Payroll run not found.');
   if(['APPROVED','CLOSED'].includes(run.status))throw new ValidationError('Approved or closed payroll cannot be recalculated.');
   const emps=(await client.query('SELECT e.id,COALESCE(es.gross_monthly,0) gross,COALESCE(es.component_values,\'{}\') component_values FROM hr_employees e LEFT JOIN LATERAL(SELECT gross_monthly,component_values FROM hr_employee_salary x WHERE x.employee_id=e.id AND x.tenant_id=e.tenant_id AND x.effective_from<=$2 AND (x.effective_to IS NULL OR x.effective_to>=$1) ORDER BY x.effective_from DESC LIMIT 1) es ON true WHERE e.tenant_id=$3 AND e.is_deleted=false AND e.employment_status=\'ACTIVE\'',[run.period_start,run.period_end,c.tenantId])).rows;
   await client.query('DELETE FROM hr_payslips WHERE payroll_run_id=$1 AND tenant_id=$2',[runId,c.tenantId]);
   let grossTotal=0,deductionTotal=0;
   const days=(new Date(run.period_end).getTime()-new Date(run.period_start).getTime())/86400000+1;
   for(const e of emps){
    const attendance=Number((await client.query('SELECT COALESCE(SUM(CASE WHEN status=\'PRESENT\' THEN 1 WHEN status=\'HALF_DAY\' THEN 0.5 ELSE 0 END),0) days FROM hr_attendance WHERE tenant_id=$1 AND employee_id=$2 AND attendance_date BETWEEN $3 AND $4',[c.tenantId,e.id,run.period_start,run.period_end])).rows[0].days);
    const payable=attendance>0?Math.min(1,attendance/days):1;
    const adj=(await client.query('SELECT COALESCE(SUM(CASE WHEN adjustment_type IN (\'EARNING\',\'BONUS\',\'INCENTIVE\') THEN amount ELSE 0 END),0) earnings,COALESCE(SUM(CASE WHEN adjustment_type NOT IN (\'EARNING\',\'BONUS\',\'INCENTIVE\') THEN amount ELSE 0 END),0) deductions FROM hr_payroll_adjustments WHERE tenant_id=$1 AND employee_id=$2 AND payroll_period_id=$3 AND approved=true',[c.tenantId,e.id,run.payroll_period_id])).rows[0];
    const loan=Number((await client.query("SELECT COALESCE(SUM(LEAST(installment_amount,outstanding)),0) amount FROM hr_payroll_loans WHERE tenant_id=$1 AND employee_id=$2 AND status='ACTIVE'",[c.tenantId,e.id])).rows[0].amount);
    const reimbursement=Number((await client.query("SELECT COALESCE(SUM(amount),0) amount FROM hr_payroll_reimbursements WHERE tenant_id=$1 AND employee_id=$2 AND payroll_period_id=$3 AND status='APPROVED'",[c.tenantId,e.id,run.payroll_period_id])).rows[0].amount);
    const earning=Number(e.gross)*payable+Number(adj.earnings)+reimbursement; const deductions=Number(adj.deductions)+loan; grossTotal+=earning; deductionTotal+=deductions;
    await client.query('INSERT INTO hr_payslips(id,tenant_id,payroll_run_id,employee_id,gross,deductions,net,earnings,deduction_details,attendance_snapshot,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,\'CALCULATED\')',[uuidV7(),c.tenantId,runId,e.id,earning,deductions,earning-deductions,JSON.stringify({salary:Number(e.gross),adjustments:Number(adj.earnings),reimbursements:reimbursement,componentValues:e.component_values}),JSON.stringify({adjustments:Number(adj.deductions),loan}),JSON.stringify({attendanceDays:attendance,periodDays:days,payableFactor:payable})]);
   }
   return(await client.query("UPDATE hr_payroll_runs SET employee_count=$2,gross_total=$3,deduction_total=$4,net_total=$3-$4,status='CALCULATED',calculated_at=NOW() WHERE id=$1 RETURNING *",[runId,emps.length,grossTotal,deductionTotal])).rows[0];
  });
 }
 async approvePayroll(c:HrContext,runId:string){await this.auth(c,'payroll','approve');if(!isUuid(runId))throw new ValidationError('Invalid payroll run id.');return this.applyWorkflowDecision(c,'HR_PAYROLL_RUN',runId,'APPROVED');}
 async closePayroll(c:HrContext,runId:string){await this.auth(c,'payroll','close');if(!isUuid(runId))throw new ValidationError('Invalid payroll run id.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const q=await client.query("UPDATE hr_payroll_runs SET status='CLOSED',closed_at=NOW() WHERE id=$1 AND tenant_id=$2 AND status='APPROVED' RETURNING *",[runId,c.tenantId]);if(!q.rowCount)throw new ValidationError('Payroll run must be APPROVED before closing.');return q.rows[0];});}
 async finalizeAttendance(c:HrContext,attendanceId:string){await this.auth(c,'attendance','update');if(!isUuid(attendanceId))throw new ValidationError('Invalid attendance id.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const q=await client.query("UPDATE hr_attendance SET finalized=true,updated_at=NOW() WHERE id=$1 AND tenant_id=$2 RETURNING *",[attendanceId,c.tenantId]);if(!q.rowCount)throw new NotFoundError('Attendance record not found.');return q.rows[0];});}
 async employeeExit(c:HrContext,employeeId:string,exitDate:string,reason?:string){await this.auth(c,'employee','update');if(!isUuid(employeeId)||!exitDate)throw new ValidationError('Employee and exit date are required.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const q=await client.query("UPDATE hr_employees SET employment_status='EXITED',exit_date=$1,updated_at=NOW(),version=version+1 WHERE id=$2 AND tenant_id=$3 RETURNING *",[exitDate,employeeId,c.tenantId]);if(!q.rowCount)throw new NotFoundError('Employee not found.');await client.query("INSERT INTO hr_employment_history(id,tenant_id,employee_id,effective_from,action,notes,created_by) VALUES($1,$2,$3,$4,'EXIT',$5,$6)",[uuidV7(),c.tenantId,employeeId,exitDate,reason??null,c.userId]);return q.rows[0];});}
 async linkUser(c:HrContext,employeeId:string,userId:string){await this.auth(c,'employee','grant_access');if(!isUuid(employeeId)||!isUuid(userId))throw new ValidationError('Invalid employee or user id.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const u=(await client.query('SELECT id,identity_id FROM users WHERE id=$1 AND tenant_id=$2 AND is_deleted=false',[userId,c.tenantId])).rows[0];if(!u)throw new NotFoundError('ERP user not found.');const q=await client.query('UPDATE hr_employees SET user_id=$1,identity_id=$2,updated_at=NOW(),version=version+1 WHERE id=$3 AND tenant_id=$4 RETURNING *',[u.id,u.identity_id,employeeId,c.tenantId]);if(!q.rowCount)throw new NotFoundError('Employee not found.');return q.rows[0];});}
 async workforceSummary(c:HrContext){await this.auth(c,'analytics','read');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const head=(await client.query("SELECT count(*)::int total,count(*) FILTER(WHERE employment_status='ACTIVE')::int active,count(*) FILTER(WHERE employment_status='EXITED')::int exited FROM hr_employees WHERE tenant_id=$1 AND is_deleted=false",[c.tenantId])).rows[0];const departments=(await client.query("SELECT d.id,d.code,d.name,count(e.id)::int headcount FROM hr_departments d LEFT JOIN hr_employees e ON e.department_id=d.id AND e.tenant_id=d.tenant_id AND e.is_deleted=false AND e.employment_status='ACTIVE' WHERE d.tenant_id=$1 AND d.is_deleted=false GROUP BY d.id,d.code,d.name ORDER BY d.name",[c.tenantId])).rows;return{headcount:head,departments};});}
}
