import { validate as isUuid, v7 as uuidV7 } from 'uuid';
import type { Pool } from 'pg';
import { ForbiddenError, NotFoundError, ValidationError } from '../../domain/errors.js';
import type { AuthorizationService } from './authorization-service.js';
import type { ModuleAccessService } from './module-access-service.js';
import { withTenantContext } from '../../infrastructure/database/tenant-context.js';
export interface HrContext { tenantId: string; branchId?: string | null; userId: string; }
const TABLES: Record<string,string> = { employees:'hr_employees', departments:'hr_departments', positions:'hr_positions', shifts:'hr_shifts', holidays:'hr_holidays', attendance:'hr_attendance', punches:'hr_attendance_punches', attendanceCorrections:'hr_attendance_corrections', leaveTypes:'hr_leave_types', leaveBalances:'hr_leave_balances', leaveRequests:'hr_leave_requests', salaryComponents:'hr_salary_components', salaryStructures:'hr_salary_structures', employeeSalary:'hr_employee_salary', payrollPeriods:'hr_payroll_periods', payrollRuns:'hr_payroll_runs', payslips:'hr_payslips', payrollAdjustments:'hr_payroll_adjustments', requisitions:'hr_recruitment_requisitions', candidates:'hr_candidates', applications:'hr_applications', interviews:'hr_interviews', performanceCycles:'hr_performance_cycles', performanceReviews:'hr_performance_reviews', trainingPrograms:'hr_training_programs', trainingRecords:'hr_training_records', compliance:'hr_compliance_records', employeeRequests:'hr_employee_requests' };
const RESOURCE: Record<string,string> = {}; Object.keys(TABLES).forEach(k=>RESOURCE[k]=k); Object.assign(RESOURCE,{employees:'employee',departments:'department',positions:'position',attendance:'attendance',attendanceCorrections:'attendance_correction',leaveTypes:'leave_type',leaveBalances:'leave_balance',leaveRequests:'leave_request',salaryComponents:'salary_component',salaryStructures:'salary_structure',employeeSalary:'employee_salary',payrollPeriods:'payroll_period',payrollRuns:'payroll_run',payslips:'payslip',payrollAdjustments:'payroll_adjustment',requisitions:'recruitment_requisition',candidates:'candidate',applications:'application',interviews:'interview',performanceCycles:'performance_cycle',performanceReviews:'performance_review',trainingPrograms:'training_program',trainingRecords:'training_record',employeeRequests:'employee_request'});
export class HrService {
 constructor(private pool:Pool,private tenantKey:string,private authorization:Pick<AuthorizationService,'hasPermission'>,private modules:Pick<ModuleAccessService,'isModuleEnabled'>){}
 private async auth(c:HrContext,r:string,a:string){if(!isUuid(c.tenantId)||!isUuid(c.userId))throw new ValidationError('Valid tenant and user context is required.');if(!(await this.modules.isModuleEnabled(c.tenantId,'hr')))throw new ForbiddenError('HR module is not enabled.');if(!(await this.authorization.hasPermission(c.tenantId,c.userId,'hr.'+r+'.'+a)))throw new ForbiddenError('HR permission denied.');}
 async list(c:HrContext,kind:string,page=1,pageSize=20,search?:string){const table=TABLES[kind],r=RESOURCE[kind];if(!table||!r)throw new ValidationError('Unknown HR resource.');await this.auth(c,r,'read');if(page<1||pageSize<1||pageSize>100)throw new ValidationError('Invalid pagination.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const params:any[]=[c.tenantId];let where='tenant_id=$1';if(search){params.push('%'+search.trim()+'%');const sf=kind==='employees'?'COALESCE(employee_no,first_name,last_name,work_email,\'\')':kind==='departments'||kind==='positions'||kind==='shifts'||kind==='leaveTypes'||kind==='salaryComponents'||kind==='salaryStructures'||kind==='payrollPeriods'||kind==='requisitions'||kind==='candidates'||kind==='performanceCycles'||kind==='trainingPrograms'?'COALESCE(code,name,\'\')':'COALESCE(status,\'\')';where+=' AND '+sf+' ILIKE $2';}const count=(await client.query('SELECT count(*)::int AS total FROM public.'+table+' WHERE '+where,params)).rows[0].total;params.push(pageSize,(page-1)*pageSize);const rows=(await client.query('SELECT * FROM public.'+table+' WHERE '+where+' ORDER BY created_at DESC LIMIT $'+(params.length-1)+' OFFSET $'+params.length,params)).rows;return{items:rows,total:count};});}
 async get(c:HrContext,kind:string,id:string){const table=TABLES[kind],r=RESOURCE[kind];if(!table||!r||!isUuid(id))throw new ValidationError('Invalid HR resource or id.');await this.auth(c,r,'read');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const q=await client.query('SELECT * FROM public.'+table+' WHERE id=$1 AND tenant_id=$2',[id,c.tenantId]);if(!q.rowCount)throw new NotFoundError('HR record not found.');return q.rows[0];});}
 async create(c:HrContext,kind:string,input:Record<string,unknown>){const table=TABLES[kind],r=RESOURCE[kind];if(!table||!r)throw new ValidationError('Unknown HR resource.');await this.auth(c,r,'create');const fields=Object.keys(input).filter(k=>/^[a-z_][a-z0-9_]*$/.test(k)&&!['id','tenant_id'].includes(k));if(!fields.length)throw new ValidationError('No fields supplied.');const vals=[uuidV7(),c.tenantId,...fields.map(k=>input[k])];return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>(await client.query('INSERT INTO public.'+table+' (id,tenant_id,'+fields.join(',')+') VALUES ('+vals.map((_,i)=>'$'+(i+1)).join(',')+') RETURNING *',vals)).rows[0]);}
 async update(c:HrContext,kind:string,id:string,input:Record<string,unknown>){const table=TABLES[kind],r=RESOURCE[kind];if(!table||!r||!isUuid(id))throw new ValidationError('Invalid HR resource or id.');await this.auth(c,r,'update');const fields=Object.keys(input).filter(k=>/^[a-z_][a-z0-9_]*$/.test(k)&&!['id','tenant_id','created_at'].includes(k));if(!fields.length)throw new ValidationError('No fields supplied.');const vals=[...fields.map(k=>input[k]),id,c.tenantId];const sets=fields.map((k,i)=>k+'=$'+(i+1)).join(',');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const q=await client.query('UPDATE public.'+table+' SET '+sets+',updated_at=NOW() WHERE id=$'+(vals.length-1)+' AND tenant_id=$'+vals.length+' RETURNING *',vals);if(!q.rowCount)throw new NotFoundError('HR record not found.');return q.rows[0];});}
 async remove(c:HrContext,kind:string,id:string){const table=TABLES[kind],r=RESOURCE[kind];if(!table||!r||!isUuid(id))throw new ValidationError('Invalid HR resource or id.');await this.auth(c,r,'delete');if(!['employees','departments','positions','shifts'].includes(kind))throw new ValidationError('This HR resource does not support deletion; use status/lifecycle fields.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const q=await client.query('UPDATE public.'+table+' SET is_deleted=true,deleted_at=NOW(),updated_at=NOW() WHERE id=$1 AND tenant_id=$2 RETURNING id',[id,c.tenantId]);if(!q.rowCount)throw new NotFoundError('HR record not found.');return q.rows[0];});}
 async punch(c:HrContext,employeeId:string,direction:'IN'|'OUT',punchedAt?:string){await this.auth(c,'attendance',direction==='IN'?'create':'update');if(!isUuid(employeeId))throw new ValidationError('Invalid employee id.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const at=punchedAt?new Date(punchedAt):new Date();if(Number.isNaN(at.getTime()))throw new ValidationError('Invalid timestamp.');await client.query('INSERT INTO hr_attendance_punches(id,tenant_id,employee_id,punched_at,direction,source) VALUES($1,$2,$3,$4,$5,\'MANUAL\')',[uuidV7(),c.tenantId,employeeId,at,direction]);const date=at.toISOString().slice(0,10),field=direction==='IN'?'check_in':'check_out';return(await client.query('INSERT INTO hr_attendance(id,tenant_id,employee_id,attendance_date,'+field+',status,source) VALUES($1,$2,$3,$4,$5,\'PRESENT\',\'MANUAL\') ON CONFLICT(tenant_id,employee_id,attendance_date) DO UPDATE SET '+field+'=EXCLUDED.'+field+',updated_at=NOW() RETURNING *',[uuidV7(),c.tenantId,employeeId,date,at])).rows[0];});}
 async calculatePayroll(c:HrContext,runId:string){await this.auth(c,'payroll','calculate');if(!isUuid(runId))throw new ValidationError('Invalid payroll run id.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const run=(await client.query('SELECT * FROM hr_payroll_runs WHERE id=$1 AND tenant_id=$2 FOR UPDATE',[runId,c.tenantId])).rows[0];if(!run)throw new NotFoundError('Payroll run not found.');const emps=(await client.query('SELECT e.id,COALESCE(es.gross_monthly,0) gross FROM hr_employees e LEFT JOIN LATERAL (SELECT gross_monthly FROM hr_employee_salary x WHERE x.employee_id=e.id AND x.tenant_id=e.tenant_id AND x.effective_from<=CURRENT_DATE ORDER BY x.effective_from DESC LIMIT 1) es ON true WHERE e.tenant_id=$1 AND e.is_deleted=false AND e.employment_status=\'ACTIVE\'',[c.tenantId])).rows;await client.query('DELETE FROM hr_payslips WHERE payroll_run_id=$1 AND tenant_id=$2',[runId,c.tenantId]);let gross=0;for(const e of emps){gross+=Number(e.gross);await client.query('INSERT INTO hr_payslips(id,tenant_id,payroll_run_id,employee_id,gross,deductions,net,earnings,status) VALUES($1,$2,$3,$4,$5,0,$5,$6,\'CALCULATED\')',[uuidV7(),c.tenantId,runId,e.id,e.gross,JSON.stringify({base:e.gross})]);}return(await client.query('UPDATE hr_payroll_runs SET employee_count=$2,gross_total=$3,deduction_total=0,net_total=$3,status=\'CALCULATED\',calculated_at=NOW() WHERE id=$1 RETURNING *',[runId,emps.length,gross])).rows[0];});}
 async linkUser(c:HrContext,employeeId:string,userId:string){await this.auth(c,'employee','grant_access');if(!isUuid(employeeId)||!isUuid(userId))throw new ValidationError('Invalid employee or user id.');return withTenantContext(this.pool,this.tenantKey,c.tenantId,async client=>{const u=(await client.query('SELECT id,identity_id FROM users WHERE id=$1 AND tenant_id=$2 AND is_deleted=false',[userId,c.tenantId])).rows[0];if(!u)throw new NotFoundError('ERP user not found.');const q=await client.query('UPDATE hr_employees SET user_id=$1,identity_id=$2,updated_at=NOW(),version=version+1 WHERE id=$3 AND tenant_id=$4 RETURNING *',[u.id,u.identity_id,employeeId,c.tenantId]);if(!q.rowCount)throw new NotFoundError('Employee not found.');return q.rows[0];});}
}
