import { validate as isUuid } from 'uuid';
import type { AuditLogger } from '../contracts/audit.js';
import type { AuthorizationService } from './authorization-service.js';
import type { ModuleAccessService } from './module-access-service.js';
import type { ManufacturingExecutionRepository } from '../../domain/contracts/manufacturing-execution.js';
import { ForbiddenError, ValidationError } from '../../domain/errors.js';
import type { WorkflowService } from './workflow-service.js';

export const MANUFACTURING_EXECUTION_PERMISSIONS = {
 capabilityRead:'manufacturing.capability.read', capabilityCreate:'manufacturing.capability.create',
 processRead:'manufacturing.process.read', processCreate:'manufacturing.process.create',
 workOrderRead:'manufacturing.work_order.read', workOrderCreate:'manufacturing.work_order.create', workOrderSchedule:'manufacturing.work_order.schedule',
 taskRead:'manufacturing.task_sheet.read', taskUpdate:'manufacturing.task_sheet.update',
 materialCreate:'manufacturing.material_requisition.create', materialIssue:'manufacturing.material_requisition.issue',
 readinessExecute:'manufacturing.readiness.execute', productionPunch:'manufacturing.production.punch',
 qualityPunch:'manufacturing.quality.punch', materialReturn:'manufacturing.material_return.create',
 varianceCreate:'manufacturing.variance.create', varianceRead:'manufacturing.variance.read',
} as const;

export class ManufacturingExecutionService {
 constructor(private readonly repo:ManufacturingExecutionRepository,private readonly auth:Pick<AuthorizationService,'hasPermission'>,private readonly modules:Pick<ModuleAccessService,'isModuleEnabled'>,private readonly audit:AuditLogger,private readonly tx:{runInTransaction<T>(cb:()=>Promise<T>):Promise<T>},private readonly workflow:Pick<WorkflowService,'onDocumentSubmitted'>){}
 private async guard(ctx:any,p:string){for(const x of ['tenantId','branchId','financialYearId','userId'])if(!isUuid(ctx[x]))throw new ValidationError(`Valid ${x} is required.`);if(!(await this.modules.isModuleEnabled(ctx.tenantId,'manufacturing')))throw new ForbiddenError('Manufacturing module is not enabled for this tenant.');if(!(await this.auth.hasPermission(ctx.tenantId,ctx.userId,p)))throw new ForbiddenError('Insufficient permission for manufacturing operation.');}
 private positive(v:any,n:string){const x=Number(v);if(!Number.isFinite(x)||x<=0)throw new ValidationError(`${n} must be greater than zero.`);return x;}
 async createTool(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.capabilityCreate);if(typeof i.code!=='string'||typeof i.name!=='string'||!i.code.trim()||!i.name.trim())throw new ValidationError('Tool code and name are required.');return this.mutate(ctx,'manufacturing.tool.created','manufacturing_tool',()=>this.repo.createTool({...i,...ctx,userId:ctx.userId}));}
 async createFixture(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.capabilityCreate);if(typeof i.code!=='string'||typeof i.name!=='string'||!i.code.trim()||!i.name.trim())throw new ValidationError('Fixture code and name are required.');return this.mutate(ctx,'manufacturing.fixture.created','manufacturing_fixture',()=>this.repo.createFixture({...i,...ctx,userId:ctx.userId}));}
 async createCalibration(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.readinessExecute);for(const x of ['entityId'])if(!isUuid(i[x]))throw new ValidationError(`${x} is required.`);if(!['MACHINE','TOOL','FIXTURE'].includes(i.entityType))throw new ValidationError('Calibration entity type is invalid.');if(typeof i.validFrom!=='string'||typeof i.validUntil!=='string')throw new ValidationError('Calibration validity dates are required.');return this.mutate(ctx,'manufacturing.calibration.created','manufacturing_calibration',()=>this.repo.createCalibration({...i,...ctx,userId:ctx.userId}));}
 async createCapability(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.capabilityCreate);if(!isUuid(i.machineId))throw new ValidationError('Machine is required.');if(typeof i.operationCode!=='string'||!i.operationCode.trim())throw new ValidationError('Operation code is required.');return this.mutate(ctx,'manufacturing.capability.created','manufacturing_machine_capability',()=>this.repo.createCapability({...i,...ctx,userId:ctx.userId,operationCode:i.operationCode.trim().toUpperCase()}));}
 async listCapabilities(ctx:any,q:any={}){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.capabilityRead);const page=Number(q.page??1),pageSize=Number(q.pageSize??20);if(page<1||pageSize<1||pageSize>100)throw new ValidationError('Invalid pagination.');return this.repo.listCapabilities(ctx,{...q,page,pageSize});}
 async createProcess(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.processCreate);if(!isUuid(i.itemId)||typeof i.revision!=='string'||!i.revision.trim())throw new ValidationError('Item and revision are required.');return this.mutate(ctx,'manufacturing.process.created','manufacturing_process_detail',()=>this.repo.createProcess({...i,...ctx,userId:ctx.userId,revision:i.revision.trim()}));}
 async addRouting(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.processCreate);if(!isUuid(i.processDetailId)||!Number.isInteger(Number(i.sequenceNo))||Number(i.sequenceNo)<1)throw new ValidationError('Process detail and positive sequence are required.');return this.mutate(ctx,'manufacturing.routing_operation.created','manufacturing_routing_operation',()=>this.repo.addRoutingOperation({...i,...ctx,userId:ctx.userId,sequenceNo:Number(i.sequenceNo)}));}
 async getProcess(ctx:any,id:string){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.processRead);if(!isUuid(id))throw new ValidationError('Valid process detail id is required.');return this.repo.getProcess(ctx,id);}
 async createWorkOrder(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.workOrderCreate);const qty=this.positive(i.plannedQuantity,'Planned quantity');if(!isUuid(i.itemId)||!isUuid(i.processDetailId)||typeof i.workOrderNumber!=='string'||!i.workOrderNumber.trim())throw new ValidationError('Work order number, item and process detail are required.');return this.mutate(ctx,'manufacturing.work_order.created','manufacturing_work_order',()=>this.repo.createWorkOrder({...i,...ctx,userId:ctx.userId,plannedQuantity:qty,workOrderNumber:i.workOrderNumber.trim()}));}
 async scheduleWorkOrder(ctx:any,id:string,bypassWorkflow=false){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.workOrderSchedule);if(!isUuid(id))throw new ValidationError('Valid work order id is required.');if(!bypassWorkflow){const current=await this.repo.getWorkOrder(ctx,id);const gate=await this.workflow.onDocumentSubmitted(ctx,'manufacturing_work_order',id,Number(current.version),`manufacturing_work_order:SCHEDULE:${id}:v${current.version}`);if(gate.status==='RUNNING')return {pendingApproval:true,workflow:null};}return this.mutate(ctx,'manufacturing.work_order.scheduled','manufacturing_work_order',()=>this.repo.scheduleWorkOrder({...ctx,userId:ctx.userId,workOrderId:id}));}
 async listWorkOrders(ctx:any,q:any={}){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.workOrderRead);const page=Number(q.page??1),pageSize=Number(q.pageSize??20);if(page<1||pageSize<1||pageSize>100)throw new ValidationError('Invalid pagination.');return this.repo.listWorkOrders(ctx,{...q,page,pageSize});}
 async getTask(ctx:any,id:string){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.taskRead);if(!isUuid(id))throw new ValidationError('Valid task sheet id is required.');return this.repo.getTaskSheet(ctx,id);}
 async updateTask(ctx:any,id:string,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.taskUpdate);if(!isUuid(id)||!Number.isInteger(Number(i.expectedVersion)))throw new ValidationError('Task id and expected version are required.');if(!['PENDING','READY','RUNNING','PAUSED','COMPLETED','CANCELLED'].includes(i.status))throw new ValidationError('Invalid task status.');return this.mutate(ctx,'manufacturing.task_sheet.updated','manufacturing_task_sheet',()=>this.repo.updateTaskStatus({...ctx,userId:ctx.userId,taskSheetId:id,expectedVersion:Number(i.expectedVersion),status:i.status}));}
 async createMaterialRequisition(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.materialCreate);if(!isUuid(i.workOrderId)||typeof i.requisitionNumber!=='string'||!Array.isArray(i.lines)||!i.lines.length)throw new ValidationError('Work order, requisition number and at least one material line are required.');for(const l of i.lines)this.positive(l.requiredQuantity,'Required quantity');return this.mutate(ctx,'manufacturing.material_requisition.created','manufacturing_material_requisition',()=>this.repo.createMaterialRequisition({...i,...ctx,userId:ctx.userId}));}
 async issueMaterial(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.materialIssue);this.positive(i.quantity,'Issue quantity');for(const x of ['requisitionLineId','warehouseId'])if(!isUuid(i[x]))throw new ValidationError(`${x} is required.`);if(typeof i.operationKey!=='string'||!i.operationKey.trim())throw new ValidationError('Operation key is required.');return this.mutate(ctx,'manufacturing.material_issued','manufacturing_material_issue',()=>this.repo.issueMaterial({...i,...ctx,userId:ctx.userId}));}
 async readiness(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.readinessExecute);for(const x of ['taskSheetId','machineId'])if(!isUuid(i[x]))throw new ValidationError(`${x} is required.`);return this.mutate(ctx,'manufacturing.readiness.checked','manufacturing_readiness_check',()=>this.repo.readinessGate({...i,...ctx,userId:ctx.userId}));}
 async punchProduction(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.productionPunch);this.positive(i.quantity,'Production quantity');if(!isUuid(i.taskSheetId)||!['GOOD','REWORK','REJECT','RETURN'].includes(i.outputType)||typeof i.operationKey!=='string'||!i.operationKey.trim())throw new ValidationError('Task, valid output type and operation key are required.');return this.mutate(ctx,'manufacturing.production.punched','manufacturing_production_output',()=>this.repo.punchProduction({...i,...ctx,userId:ctx.userId}));}
 async punchQuality(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.qualityPunch);this.positive(i.inspectedQuantity,'Inspected quantity');for(const x of ['acceptedQuantity','rejectedQuantity','reworkQuantity','returnedQuantity'])if(Number(i[x]??0)<0)throw new ValidationError(`${x} cannot be negative.`);if(!isUuid(i.taskSheetId))throw new ValidationError('Task sheet is required.');const accepted=Number(i.acceptedQuantity??0),rejected=Number(i.rejectedQuantity??0),rework=Number(i.reworkQuantity??0),returned=Number(i.returnedQuantity??0);if(Number(i.inspectedQuantity)!==accepted+rejected+rework+returned)throw new ValidationError('Inspected Qty must equal Accepted + Rejected + Rework + Return.');return this.mutate(ctx,'manufacturing.quality.punched','manufacturing_quality_output',()=>this.repo.punchQuality({...i,...ctx,userId:ctx.userId}));}
 async materialReturn(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.materialReturn);this.positive(i.quantity,'Return quantity');for(const x of ['workOrderId','warehouseId','itemId'])if(!isUuid(i[x]))throw new ValidationError(`${x} is required.`);for(const x of ['returnNumber','operationKey'])if(typeof i[x]!=='string'||!i[x].trim())throw new ValidationError(`${x} is required.`);return this.mutate(ctx,'manufacturing.material_return.created','manufacturing_material_return',()=>this.repo.createMaterialReturn({...i,...ctx,userId:ctx.userId}));}
 async variance(ctx:any,i:any){await this.guard(ctx,MANUFACTURING_EXECUTION_PERMISSIONS.varianceCreate);this.positive(i.quantity,'Variance quantity');if(Number(i.unitCost)<0||!Number.isFinite(Number(i.unitCost)))throw new ValidationError('Unit cost must be non-negative.');if(!isUuid(i.workOrderId)||!['REWORK','REJECTION','SCRAP','MATERIAL_RETURN'].includes(i.varianceType))throw new ValidationError('Work order and valid variance type are required.');return this.mutate(ctx,'manufacturing.variance.created','manufacturing_variance_cost',()=>this.repo.createVariance({...i,...ctx,userId:ctx.userId}));}
 private async mutate(ctx:any,action:string,resourceType:string,fn:()=>Promise<any>){return this.tx.runInTransaction(async()=>{const result=await fn();await this.audit.record({tenantId:ctx.tenantId,actorUserId:ctx.userId,action,resourceType,resourceId:result?.id??null,outcome:'success'},{requireTransaction:true});return result;});}
}
