      ['supplier', 'update'],
      ['supplier', 'delete'],
      ['requisition', 'read'],
      ['requisition', 'create'],
      ['requisition', 'update'],
      ['requisition', 'submit'],
      ['requisition', 'cancel'],
      ['order', 'read'],
      ['order', 'create'],
      ['order', 'update'],
      ['order', 'submit'],
      ['order', 'cancel'],
      ['receipt', 'read'],
      ['receipt', 'create'],
      ['receipt', 'update'],
      ['receipt', 'complete'],
      ['receipt', 'cancel'],
    ] as const