import { validate as isUuid } from 'uuid';
import type { AuditLogger } from '../contracts/audit.js';
import type { AuthorizationService } from './authorization-service.js';
import type { ModuleAccessService } from './module-access-service.js';
import type { WorkflowRepository, WorkflowContext, WorkflowDefinitionInput, WorkflowDecision, WorkflowApprovedHandler } from '../../domain/contracts/workflow.js';
import { ForbiddenError, ValidationError, NotFoundError } from '../../domain/errors.js';

export const WORKFLOW_PERMISSIONS={definitionRead:'workflow.definition.read',definitionCreate:'workflow.definition.create',definitionPublish:'workflow.definition.publish',taskRead:'workflow.task.read',taskDecide:'workflow.task.decide'} as const;
export class WorkflowService {
 private handlers=new Map<string,WorkflowApprovedHandler>();
 constructor(private readonly repo:WorkflowRepository,private readonly auth:Pick<AuthorizationService,'hasPermission'>,private readonly modules:Pick<ModuleAccessService,'isModuleEnabled'>,private readonly audit:AuditLogger){}
 registerApprovedHandler(documentType:string,action:string,handler:WorkflowApprovedHandler){this.handlers.set(documentType+':'+action,handler);}
 private async guard(c:WorkflowContext,p:string){if(!isUuid(c.tenantId)||!isUuid(c.branchId)||!isUuid(c.userId))throw new ValidationError('Valid tenant, branch, and user context is required.');if(!(await this.modules.isModuleEnabled(c.tenantId,'core')))throw new ForbiddenError('Core module is not enabled.');if(!(await this.auth.hasPermission(c.tenantId,c.userId,p)))throw new ForbiddenError('Insufficient workflow permission.');}
 async createDefinition(c:WorkflowContext,i:WorkflowDefinitionInput){await this.guard(c,WORKFLOW_PERMISSIONS.definitionCreate);if(!i.code?.trim()||!i.name?.trim()||!i.documentType?.trim()||!i.action?.trim()||!Array.isArray(i.steps)||!i.steps.length)throw new ValidationError('Workflow code, name, document type, action and steps are required.');const steps=i.steps.map((s:any,n)=>({step:Number(s.step??n+1),roleId:s.roleId,requiredApprovals:Number(s.requiredApprovals??1)}));if(steps.some((s:any)=>!isUuid(s.roleId)||s.step<1||s.requiredApprovals<1))throw new ValidationError('Each workflow step requires a valid role and positive required approvals.');return this.repo.createDefinition(c,{...i,steps});}
 async listDefinitions(c:WorkflowContext){await this.guard(c,WORKFLOW_PERMISSIONS.definitionRead);return this.repo.listDefinitions(c);}
 async publishDefinition(c:WorkflowContext,id:string){await this.guard(c,WORKFLOW_PERMISSIONS.definitionPublish);if(!isUuid(id))throw new ValidationError('Valid workflow definition ID is required.');return this.repo.publishDefinition(c,id);}
 async startIfRequired(c:WorkflowContext,i:{documentType:string;action:string;documentId:string;documentVersion:number;operationKey:string}){if(!isUuid(i.documentId)||!Number.isInteger(i.documentVersion)||!i.operationKey?.trim())throw new ValidationError('Workflow document ID, version, and operation key are required.');const d=await this.repo.findPublished(c,i.documentType,i.action);if(!d)return {required:false,approved:true,instance:null};const instance=await this.repo.startInstance(c,{...i,definitionId:d.id,definitionVersion:d.version,steps:d.steps});return {required:true,approved:instance.status==='APPROVED',instance};}
 async listTasks(c:WorkflowContext){await this.guard(c,WORKFLOW_PERMISSIONS.taskRead);return this.repo.listTasks(c,true);}
 async decide(c:WorkflowContext,taskId:string,decision:WorkflowDecision,comments?:string){await this.guard(c,WORKFLOW_PERMISSIONS.taskDecide);if(!isUuid(taskId)||!['APPROVE','REJECT','RETURN'].includes(decision))throw new ValidationError('Valid task and decision are required.');const result=await this.repo.decide(c,taskId,decision,comments);await this.audit.record({tenantId:c.tenantId,actorUserId:c.userId,action:'workflow.task.decision',resourceType:'workflow_task',resourceId:taskId,outcome:'success',metadata:{decision}},{requireTransaction:true});if(result.status==='APPROVED'){const h=this.handlers.get(result.document_type+':'+result.action);if(h)await h(c,result);}return result;}
 async getInstance(c:WorkflowContext,id:string){await this.guard(c,WORKFLOW_PERMISSIONS.taskRead);const r=await this.repo.getInstance(c,id);if(!r)throw new NotFoundError('Workflow instance not found.');return r;}
}