import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'workflow_service.dart';
class WorkflowScreen extends StatefulWidget { const WorkflowScreen({super.key}); @override State<WorkflowScreen> createState()=>_WorkflowScreenState(); }
class _WorkflowScreenState extends State<WorkflowScreen> {
 final s=GetIt.I<WorkflowService>(); int tab=0;
 final code=TextEditingController(),name=TextEditingController(),doc=TextEditingController(),action=TextEditingController(),role=TextEditingController(),comments=TextEditingController();
 @override void initState(){super.initState();WidgetsBinding.instance.addPostFrameCallback((_)=>s.load());}
 @override void dispose(){for(final c in [code,name,doc,action,role,comments])c.dispose();super.dispose();}
 Future<void> run(Future<dynamic> Function() f)async{final v=await f();if(mounted)setState((){});if(v!=null&&mounted)ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Workflow operation completed.')));}
 Widget field(String label,TextEditingController c)=>Padding(padding:const EdgeInsets.only(bottom:10),child:TextField(controller:c,decoration:InputDecoration(labelText:label,border:const OutlineInputBorder())));
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Workflow & BPM')),body:Column(children:[if(s.error!=null)MaterialBanner(content:Text(s.error!),actions:[TextButton(onPressed:()=>setState(()=>s.error=null),child:const Text('Dismiss'))]),Padding(padding:const EdgeInsets.all(12),child:Row(children:[ChoiceChip(label:const Text('Approval Inbox'),selected:tab==0,onSelected:(_)=>setState(()=>tab=0)),const SizedBox(width:8),ChoiceChip(label:const Text('Definitions'),selected:tab==1,onSelected:(_)=>setState(()=>tab=1)),const Spacer(),IconButton(onPressed:s.load,icon:const Icon(Icons.refresh))])),Expanded(child:Padding(padding:const EdgeInsets.fromLTRB(20,0,20,20),child:tab==0?_tasks():_definitions()))]));
 Widget _tasks()=>ListView(children:[Text('Pending approvals',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:12),if(s.tasks.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(24),child:Text('No pending workflow tasks.'))),...s.tasks.map((t)=>Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.approval_outlined)),title:Text('${t['document_type']??''} • ${t['action']??''}'),subtitle:Text('Document: ${t['document_id']??''}\nStep ${t['step']??''} • ${t['status']??'PENDING'}'),isThreeLine:true,trailing:Wrap(spacing:4,children:[FilledButton(onPressed:()=>run(()=>s.decide('${t['id']}','APPROVE',comments.text)),child:const Text('Approve')),OutlinedButton(onPressed:()=>run(()=>s.decide('${t['id']}','REJECT',comments.text)),child:const Text('Reject')),IconButton(onPressed:()=>run(()=>s.decide('${t['id']}','RETURN',comments.text)),icon:const Icon(Icons.undo))])))),const SizedBox(height:12),field('Decision comments (optional)',comments)]);
 Widget _definitions()=>ListView(children:[Row(children:[Expanded(child:Text('Workflow definitions',style:Theme.of(context).textTheme.headlineSmall)),FilledButton.icon(onPressed:_create,icon:const Icon(Icons.add),label:const Text('New definition'))]),const SizedBox(height:12),...s.definitions.map((d)=>Card(child:ListTile(title:Text('${d['name']??''} (${d['code']??''})'),subtitle:Text('${d['document_type']??''} / ${d['action']??''} • ${d['status']??'DRAFT'}'),trailing:d['status']=='PUBLISHED'?const Chip(label:Text('Published')):FilledButton(onPressed:()=>run(()=>s.publish('${d['id']}')),child:const Text('Publish'))))) ]);
 Future<void> _create()async{final result=await showDialog<Map<String,dynamic>>(context:context,builder:(_)=>AlertDialog(title:const Text('Create workflow definition'),content:SingleChildScrollView(child:Column(mainAxisSize:MainAxisSize.min,children:[field('Code',code),field('Name',name),field('Document type',doc),field('Action',action),field('Approver role ID',role)])),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Cancel')),FilledButton(onPressed:(){if([code,name,doc,action,role].any((x)=>x.text.trim().isEmpty))return;Navigator.pop(context,{'code':code.text.trim(),'name':name.text.trim(),'documentType':doc.text.trim(),'action':action.text.trim(),'steps':[{'step':1,'roleId':role.text.trim(),'requiredApprovals':1}]});},child:const Text('Create')])));if(result!=null)await run(()=>s.createDefinition(result));}
}