#!/usr/bin/env python3
"""Deterministic repository inventory for NEW_ERP_FINAL.

This tool does not use an LLM and does not decide architecture. It inventories
repository facts and selected documentation metadata so an AI assistant can
navigate the repository without ingesting the entire tree into context.

Usage:
    python tools/ai/repository_scanner.py
    python tools/ai/repository_scanner.py --root . --output .ai/generated
"""

from __future__ import annotations

import argparse
import hashlib
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

IGNORED_DIRS = {
    ".git", ".idea", ".vscode", "node_modules", "dist", "build", "coverage",
    "__pycache__", ".pytest_cache", ".mypy_cache", ".next", "target", "bin", "obj",
}

TEXT_EXTENSIONS = {
    ".md", ".markdown", ".txt", ".json", ".yaml", ".yml", ".toml", ".xml",
    ".cs", ".ts", ".tsx", ".js", ".jsx", ".py", ".java", ".kt", ".go", ".rs",
    ".sql", ".sh", ".ps1", ".csproj", ".sln", ".props", ".targets",
}


def walk_files(root: Path):
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        rel_parts = path.relative_to(root).parts
        if any(part in IGNORED_DIRS for part in rel_parts):
            continue
        yield path


def read_text(path: Path, limit: int = 12000) -> str | None:
    if path.suffix.lower() not in TEXT_EXTENSIONS and path.name not in {"Dockerfile", "Makefile", "LICENSE"}:
        return None
    try:
        return path.read_text(encoding="utf-8", errors="replace")[:limit]
    except OSError:
        return None


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def detect_technologies(paths: list[Path], root: Path) -> list[str]:
    names = {p.name.lower() for p in paths}
    suffixes = Counter(p.suffix.lower() for p in paths)
    technologies: list[str] = []

    checks = [
        ("Node.js / JavaScript", {"package.json", "package-lock.json", "pnpm-lock.yaml", "yarn.lock"}),
        ("TypeScript", set(), ".ts"),
        ("Python", {"pyproject.toml", "requirements.txt", "poetry.lock"}),
        (".NET", {"global.json", "nuget.config"}, ".cs"),
        ("Java", {"pom.xml", "build.gradle", "gradlew"}),
        ("Go", {"go.mod", "go.sum"}),
        ("Rust", {"cargo.toml", "cargo.lock"}),
        ("Docker", {"dockerfile", "compose.yaml", "compose.yml", "docker-compose.yml"}),
        ("SQL", set(), ".sql"),
    ]

    for item in checks:
        label, marker_names, *suffix = item
        if marker_names.intersection(names) or (suffix and suffixes[suffix[0]] > 0):
            technologies.append(label)

    if (root / ".github").exists():
        technologies.append("GitHub repository automation/configuration")
    return technologies


def extract_adr_status(path: Path) -> str:
    text = read_text(path) or ""
    match = re.search(r"(?:^|\n)\s*\*\*Status\*\*\s*:\s*([^\n]+)", text, re.I)
    if not match:
        match = re.search(r"(?:^|\n)\s*Status\s*:\s*([^\n]+)", text, re.I)
    return match.group(1).strip() if match else "Unknown"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".", help="Repository root")
    parser.add_argument("--output", default=".ai/generated", help="Generated artifact directory")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    output = (root / args.output).resolve()
    output.mkdir(parents=True, exist_ok=True)

    files = sorted(walk_files(root))
    rel_files = [p.relative_to(root).as_posix() for p in files]
    docs = [p for p in files if p.is_relative_to(root / "docs")]
    adrs = [p for p in docs if p.is_relative_to(root / "docs/10-adr") and p.suffix.lower() in {".md", ".markdown"}]

    counts = Counter(Path(name).suffix.lower() or "[no extension]" for name in rel_files)
    technologies = detect_technologies(files, root)

    generated_at = datetime.now(timezone.utc).isoformat()
    inventory_lines = [
        "# Generated Repository Inventory",
        "",
        "> Generated by `tools/ai/repository_scanner.py`. This file contains repository facts only; it is not architectural authority.",
        "",
        f"Generated: `{generated_at}`",
        f"Files discovered: **{len(files)}**",
        f"Documentation files: **{len(docs)}**",
        f"ADR candidate files: **{len(adrs)}**",
        "",
        "## Detected technologies",
        "",
    ]
    inventory_lines += [f"- {tech}" for tech in technologies] or ["- No technology markers detected."]
    inventory_lines += ["", "## File-type distribution", "", "| Extension | Count |", "|---|---:|"]
    inventory_lines += [f"| `{ext}` | {count} |" for ext, count in sorted(counts.items())]
    inventory_lines += ["", "## Top-level areas", ""]
    top_level = Counter(name.split("/", 1)[0] for name in rel_files)
    inventory_lines += [f"- `{name}/` — {count} files" for name, count in sorted(top_level.items())]
    inventory_lines += ["", "## Repository files", "", "```text"]
    inventory_lines += rel_files
    inventory_lines += ["```", ""]
    (output / "repository-inventory.md").write_text("\n".join(inventory_lines), encoding="utf-8")

    doc_lines = [
        "# Generated Documentation Index",
        "",
        "> Generated from file paths and lightweight metadata. The authoritative meaning remains in the documents themselves.",
        "",
        f"Generated: `{generated_at}`",
        "",
        "## Documentation files",
        "",
    ]
    for path in docs:
        rel = path.relative_to(root).as_posix()
        title = path.stem.replace("-", " ").replace("_", " ").strip()
        text = read_text(path, 4000) or ""
        heading = re.search(r"^#\s+(.+)$", text, re.M)
        if heading:
            title = heading.group(1).strip()
        doc_lines.append(f"- `{rel}` — {title}")

    doc_lines += ["", "## ADR status", "", "| ADR | Status | SHA-256 |", "|---|---|---|"]
    for path in adrs:
        rel = path.relative_to(root).as_posix()
        doc_lines.append(f"| `{rel}` | {extract_adr_status(path)} | `{sha256(path)[:16]}` |")
    (output / "documentation-index.md").write_text("\n".join(doc_lines) + "\n", encoding="utf-8")

    print(f"Repository scan complete: {len(files)} files")
    print(f"Generated: {output / 'repository-inventory.md'}")
    print(f"Generated: {output / 'documentation-index.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
