import { type FastifyPluginAsync, type FastifyRequest } from 'fastify';

import { NotFoundError, ValidationError } from '../../../domain/errors.js';
import { requireAuth, requirePermission } from '../middleware/auth.js';
import { recordSecurityEvent } from '../security-audit.js';

type EnterpriseStatus = 'active' | 'inactive' | 'archived';
type UserStatus = 'active' | 'inactive' | 'locked' | 'pending_verification';

interface IdParams { id: string; }
interface OrganizationParams { organizationId: string; }
interface OrganizationBranchParams extends OrganizationParams { branchId: string; }
interface UserOrganizationAccessParams { userId: string; organizationId: string; }
interface UserBranchAccessParams { userId: string; branchId: string; }
interface CreateOrganizationBody { name?: string; legalName?: string | null; gstNo?: string | null; panNo?: string | null; cinNo?: string | null; email?: string | null; phone?: string | null; website?: string | null; baseCurrency?: string; fiscalCalendar?: string; status?: EnterpriseStatus; isDefault?: boolean; remarks?: string | null; }
interface UpdateOrganizationBody extends CreateOrganizationBody { code?: string; }
interface CreateBranchBody { name?: string; status?: EnterpriseStatus; isHeadOffice?: boolean; isDefault?: boolean; addressLine1?: string | null; addressLine2?: string | null; city?: string | null; district?: string | null; state?: string | null; country?: string | null; postalCode?: string | null; timezone?: string; remarks?: string | null; }
interface UpdateBranchBody extends CreateBranchBody { code?: string; }
interface UpdateUserBody { username?: string; email?: string; organizationId?: string | null; defaultBranchId?: string | null; status?: UserStatus; }
const getTenantIdFromRequest = (request: FastifyRequest): string | null => request.tenantId ?? null;
const trimmed = (value: string | null | undefined): string | undefined => value?.trim() || undefined;

const coreEnterpriseRoutes: FastifyPluginAsync = async (fastify) => {
  fastify.post<{ Body: CreateOrganizationBody }>('/organizations', { preHandler: [requireAuth, requirePermission('organization.create')] }, async (request, reply) => {
    const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.');
    const body = request.body; const organization = await request.server.coreEnterpriseService.createOrganization(tenantId, { name: trimmed(body.name), legalName: trimmed(body.legalName), gstNo: trimmed(body.gstNo), panNo: trimmed(body.panNo), cinNo: trimmed(body.cinNo), email: trimmed(body.email), phone: trimmed(body.phone), website: trimmed(body.website), baseCurrency: trimmed(body.baseCurrency) ?? 'USD', fiscalCalendar: trimmed(body.fiscalCalendar) ?? 'standard', status: body.status ?? 'active', isDefault: body.isDefault ?? false, remarks: body.remarks ?? null }); reply.code(201); return { success: true, organization };
  });
  fastify.get('/organizations', { preHandler: [requireAuth, requirePermission('organization.read')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); return { success: true, organizations: await request.server.coreEnterpriseService.listOrganizations(tenantId) }; });
  fastify.get<{ Params: IdParams }>('/organizations/:id', { preHandler: [requireAuth, requirePermission('organization.read')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const organization = await request.server.coreEnterpriseService.getOrganization(tenantId, request.params.id.trim()); if (!organization) throw new NotFoundError('Organization not found.'); return { success: true, organization }; });
  fastify.patch<{ Params: IdParams; Body: UpdateOrganizationBody }>('/organizations/:id', { preHandler: [requireAuth, requirePermission('organization.update')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const body = request.body; const updated = await request.server.coreEnterpriseService.updateOrganization(tenantId, request.params.id.trim(), { code: body.code, name: body.name, legalName: body.legalName, gstNo: body.gstNo, panNo: body.panNo, email: body.email, phone: body.phone, website: body.website, baseCurrency: body.baseCurrency, fiscalCalendar: body.fiscalCalendar, status: body.status, isDefault: body.isDefault, remarks: body.remarks }); if (!updated) throw new NotFoundError('Organization not found.'); return { success: true, organization: updated }; });
  fastify.post<{ Params: IdParams }>('/organizations/:id/deactivate', { preHandler: [requireAuth, requirePermission('organization.deactivate')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const deactivated = await request.server.coreEnterpriseService.deactivateOrganization(tenantId, request.params.id.trim()); if (!deactivated) throw new NotFoundError('Organization not found.'); await recordSecurityEvent(request, { tenantId, actorUserId: request.user?.id, action: 'organization.deactivate', resourceType: 'organization', resourceId: request.params.id, outcome: 'success', metadata: {} }); return { success: true, deactivated: true }; });
  fastify.post<{ Params: IdParams }>('/organizations/:id/activate', { preHandler: [requireAuth, requirePermission('organization.activate')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const activated = await request.server.coreEnterpriseService.activateOrganization(tenantId, request.params.id.trim()); if (!activated) throw new NotFoundError('Organization not found.'); await recordSecurityEvent(request, { tenantId, actorUserId: request.user?.id, action: 'organization.activate', resourceType: 'organization', resourceId: request.params.id, outcome: 'success', metadata: {} }); return { success: true, activated: true }; });
  fastify.delete<{ Params: IdParams }>('/organizations/:id', { preHandler: [requireAuth, requirePermission('organization.delete')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const deleted = await request.server.coreEnterpriseService.deleteOrganization(tenantId, request.params.id.trim()); if (!deleted) throw new NotFoundError('Organization not found.'); return { success: true, deleted: true }; });
  fastify.post<{ Params: OrganizationParams; Body: CreateBranchBody }>('/organizations/:organizationId/branches', { preHandler: [requireAuth, requirePermission('branch.create')] }, async (request, reply) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const body = request.body; const branch = await request.server.coreEnterpriseService.createBranch(tenantId, request.params.organizationId.trim(), { name: trimmed(body.name), status: body.status ?? 'active', isHeadOffice: body.isHeadOffice ?? false, isDefault: body.isDefault ?? false, addressLine1: body.addressLine1 ?? null, addressLine2: body.addressLine2 ?? null, city: body.city ?? null, district: body.district ?? null, state: body.state ?? null, country: body.country ?? null, postalCode: body.postalCode ?? null, timezone: body.timezone ?? 'UTC', remarks: body.remarks ?? null }); reply.code(201); return { success: true, branch }; });
  fastify.get<{ Params: OrganizationParams }>('/organizations/:organizationId/branches', { preHandler: [requireAuth, requirePermission('branch.read')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); return { success: true, branches: await request.server.coreEnterpriseService.listBranches(tenantId, request.params.organizationId.trim()) }; });
  fastify.get<{ Params: OrganizationBranchParams }>('/organizations/:organizationId/branches/:branchId', { preHandler: [requireAuth, requirePermission('branch.read')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const branch = await request.server.coreEnterpriseService.getBranch(tenantId, request.params.organizationId.trim(), request.params.branchId.trim()); if (!branch) throw new NotFoundError('Branch not found.'); return { success: true, branch }; });
  fastify.patch<{ Params: OrganizationBranchParams; Body: UpdateBranchBody }>('/organizations/:organizationId/branches/:branchId', { preHandler: [requireAuth, requirePermission('branch.update')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const body = request.body; const updated = await request.server.coreEnterpriseService.updateBranch(tenantId, request.params.organizationId.trim(), request.params.branchId.trim(), { code: body.code, name: body.name, status: body.status, isHeadOffice: body.isHeadOffice, isDefault: body.isDefault, addressLine1: body.addressLine1, addressLine2: body.addressLine2, city: body.city, district: body.district, state: body.state, country: body.country, postalCode: body.postalCode, timezone: body.timezone, remarks: body.remarks }); if (!updated) throw new NotFoundError('Branch not found.'); return { success: true, branch: updated }; });
  fastify.post<{ Params: OrganizationBranchParams }>('/organizations/:organizationId/branches/:branchId/deactivate', { preHandler: [requireAuth, requirePermission('branch.deactivate')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const deactivated = await request.server.coreEnterpriseService.deactivateBranch(tenantId, request.params.organizationId.trim(), request.params.branchId.trim()); if (!deactivated) throw new NotFoundError('Branch not found.'); return { success: true, deactivated: true }; });
  fastify.post<{ Params: OrganizationBranchParams }>('/organizations/:organizationId/branches/:branchId/activate', { preHandler: [requireAuth, requirePermission('branch.activate')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const activated = await request.server.coreEnterpriseService.activateBranch(tenantId, request.params.organizationId.trim(), request.params.branchId.trim()); if (!activated) throw new NotFoundError('Branch not found.'); return { success: true, activated: true }; });
  fastify.delete<{ Params: OrganizationBranchParams }>('/organizations/:organizationId/branches/:branchId', { preHandler: [requireAuth, requirePermission('branch.delete')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const deleted = await request.server.coreEnterpriseService.deleteBranch(tenantId, request.params.organizationId.trim(), request.params.branchId.trim()); if (!deleted) throw new NotFoundError('Branch not found.'); return { success: true, deleted: true }; });
  fastify.get('/users', { preHandler: [requireAuth, requirePermission('user.read')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); return { success: true, users: await request.server.coreEnterpriseService.listUsers(tenantId) }; });
  fastify.get<{ Params: IdParams }>('/users/:id', { preHandler: [requireAuth, requirePermission('user.read')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const user = await request.server.coreEnterpriseService.getUser(tenantId, request.params.id.trim()); if (!user) throw new NotFoundError('User not found.'); return { success: true, user }; });
  fastify.get<{ Params: IdParams }>('/users/:id/access', { preHandler: [requireAuth, requirePermission('user.read')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const userId = request.params.id.trim(); const user = await request.server.coreEnterpriseService.getUser(tenantId, userId); if (!user) throw new NotFoundError('User not found.'); const access = await request.server.coreEnterpriseService.getUserAccess(tenantId, userId); return { success: true, userId, organizations: access.organizations, branches: access.branches }; });
  fastify.patch<{ Params: IdParams; Body: UpdateUserBody }>('/users/:id', { preHandler: [requireAuth, requirePermission('user.update')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const body = request.body; const updated = await request.server.coreEnterpriseService.updateUser(tenantId, request.params.id.trim(), { username: body.username, email: body.email, organizationId: body.organizationId, defaultBranchId: body.defaultBranchId, status: body.status }); if (!updated) throw new NotFoundError('User not found.'); return { success: true, user: updated }; });
  fastify.post<{ Params: UserOrganizationAccessParams }>('/users/:userId/organizations/:organizationId/access', { preHandler: [requireAuth, requirePermission('user.update')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const assigned = await request.server.coreEnterpriseService.assignUserToOrganization(tenantId, request.params.userId.trim(), request.params.organizationId.trim()); if (!assigned) throw new NotFoundError('User or organization not found.'); return { success: true, assigned: true }; });
  fastify.post<{ Params: UserBranchAccessParams }>('/users/:userId/branches/:branchId/access', { preHandler: [requireAuth, requirePermission('user.update')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const assigned = await request.server.coreEnterpriseService.assignUserToBranch(tenantId, request.params.userId.trim(), request.params.branchId.trim()); if (!assigned) throw new NotFoundError('User or branch not found.'); return { success: true, assigned: true }; });
  fastify.post<{ Params: IdParams }>('/users/:id/activate', { preHandler: [requireAuth, requirePermission('user.activate')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const activated = await request.server.coreEnterpriseService.activateUser(tenantId, request.params.id.trim()); if (!activated) throw new NotFoundError('User not found.'); return { success: true, activated: true }; });
  fastify.post<{ Params: IdParams }>('/users/:id/deactivate', { preHandler: [requireAuth, requirePermission('user.deactivate')] }, async (request) => { const tenantId = request.tenantId ?? getTenantIdFromRequest(request); if (!tenantId) throw new ValidationError('Tenant context is required.'); const deactivated = await request.server.coreEnterpriseService.deactivateUser(tenantId, request.params.id.trim()); if (!deactivated) throw new NotFoundError('User not found.'); return { success: true, deactivated: true }; });
};
export default coreEnterpriseRoutes;
