import type { FastifyPluginAsync } from 'fastify';
import { requireAuth, requirePermission } from '../middleware/auth.js';
import { parsePaginationQuery } from '../pagination.js';
import { requestParam } from '../request-input.js';
import type { DeliveryRecord } from '../../../domain/contracts/repositories.js';
function ctx(r:any){return {tenantId:r.tenantId,organizationId:r.user.organizationId,branchId:r.user.branchId??r.user.defaultBranchId,financialYearId:r.user.financialYearId,userId:r.user.id};}
function out(x:DeliveryRecord){const {tenantId:_t,...v}=x;return v;}
const deliveryRoutes:FastifyPluginAsync=async(f)=>{f.post('/sales/deliveries',{preHandler:[requireAuth,requirePermission('sales.delivery.create')]},async(r:any,h)=>{const x=await f.deliveryService.create(ctx(r),r.body);h.code(201);return {success:true,delivery:out(x)};});f.get('/sales/deliveries',{preHandler:[requireAuth,requirePermission('sales.delivery.read')]},async(r:any)=>{const p=parsePaginationQuery(r.query);const x=await f.deliveryService.list(ctx(r),p);return {success:true,deliveries:x.items.map(out),metadata:{page:p.page,page_size:p.pageSize,total:x.total,total_pages:Math.ceil(x.total/p.pageSize),order:p.order}};});f.get('/sales/deliveries/:id',{preHandler:[requireAuth,requirePermission('sales.delivery.read')]},async(r:any)=>({success:true,delivery:out(await f.deliveryService.get(ctx(r),requestParam(r.params,'id')??''))}));f.patch('/sales/deliveries/:id',{preHandler:[requireAuth,requirePermission('sales.delivery.update')]},async(r:any)=>({success:true,delivery:out(await f.deliveryService.update(ctx(r),requestParam(r.params,'id')??'',r.body))}));for(const s of ['dispatch','deliver','complete','cancel'] as const)f.post(`/sales/deliveries/:id/${s}`,{preHandler:[requireAuth,requirePermission(`sales.delivery.${s}`)]},async(r:any)=>({success:true,delivery:out(await f.deliveryService.transition(ctx(r),requestParam(r.params,'id')??'',s==='dispatch'?'DISPATCHED':s==='deliver'?'DELIVERED':s==='complete'?'COMPLETED':'CANCELLED',r.body.expectedVersion))}));};
export default deliveryRoutes;
